### ISSUE TITLE
Add support for specifying accessToken in requests

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#113]
For simulating requests coming from linked accounts

**Comment by xnejp03** [comment]
Yes please, necessary for linked accounts

**Comment by jkelvie** [comment]
Hi @xnejp03 just realized I neglected to close this issue.

We actually added this feature. You can set the accessToken on BSTAlexa by calling:
`alexa.context().setAccessToken("ACCESS_TOKEN")`

This is part of our programmatic API. Let me know if that makes sense and works for you.

**Comment by xnejp03** [comment]
Thanks @jkelvie . I was more thinking about using in via bst speak, for example (either as a commnd line parameter or as a part of some config file).

**Comment by jkelvie** [comment]
Hi @xnejp03 this makes sense and I see that would be useful....I'll keep this issue open to keep track of it.
