### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by alperkal** [bespoken/bst#154]
Hi,
After the winter timezone change, I started having problems with bst proxy. Although system date is correct (date command in command line gives correct time), when I start proxy, log output of the bst proxy are 1 hour behind! As a result, once proxy forwards the request to my service, it is rejected with following error:

`
java.lang.SecurityException: Failed to verify the signature/certificate for the provided speechlet request
	at com.amazon.speech.speechlet.authentication.SpeechletRequestSignatureVerifier.checkRequestSignature(SpeechletRequestSignatureVerifier.java:98) ~[alexa-skills-kit-1.1.3.jar:na]
`

a quick google search shows that this can happen if the request time greatly differs from the server time 

https://webcache.googleusercontent.com/search?q=cache:s5bY7b7-snkJ:https://forums.developer.amazon.com/questions/30523/failed-to-verify-the-signaturecertificate-using-ja.html+&cd=2&hl=en&ct=clnk&gl=at

Do you have an idea why this happens?

Thanks

**Comment by OpenDog** [comment]
The line number in the trace points to a signature verification problem, not the Alexa specific timestamp check (to protect against hacks with old requests). But the signature verification can also fail with timestamp problems. 

We will look into the timestamp problem right away. It should be quick.

**Comment by OpenDog** [comment]
I tried the proxy on my mac and I get the right UTC timestamps. I also checked what date the actual skill sees and that is correct too.

So I need more info. 

What OS you are using? How do you proxy? Directly (bst proxy lambda) or via http? Node version. What is the date your Node sees (type Date() at the node prompt).

**Comment by alperkal** [comment]
It's pretty weird, I'm also using macosx
versions are:
BST: v0.8.4  Node: v4.6.1

Node Date() function correctly shows the date
I run bst as http proxy (bst proxy http 9999)

**Comment by OpenDog** [comment]
That is actually a pretty old BST. The latest is v0.9.14. Can you try it with the latest? I have to admit I'm not sure if that will help... :-)

**Comment by OpenDog** [comment]
Alper, forgive me the question. But you realize that the logs are in UTC time. They are supposed to show 1 hour less the your Vienna, AT time. 

The problem may not be timestamp. If your test payload isn't coming from Amazon and your signature verification is on, it will fail. BST doesn't provide you with the signature headers.
