### ISSUE TITLE
[Logless] Capture Crashes

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/bst#163]
When performing final integration testing (not using proxy), if a crash occurs you don't get the logs in logless.  You must instead go to CloudWatch to see what happened with the crash.

**Comment by jkelvie** [comment]
What type of crash are you referring to? We capture exceptions, both sync and async (unhandled exceptions) with Logless.

**Comment by michaelmyers** [comment]
This already exists in the stack field, closing.

**Comment by michaelmyers** [comment]
FYI, I was noticing the JavaScript crash logs were not showing up.  I traced it to the alexa-sdk which was overriding the built-in bst exception handling.  I have made a pull request over there to remove it: https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/46
