### ISSUE TITLE
Cross-platform Alexa/Home support

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#174]

**Comment by GitTom** [comment]
I started updating my skill to support home/actions, but then came across postings from Google people that indicated that there had been a change of plans at google:  that they now expect most skills for Home to be developed using API.AI and their webhooks, and that the actions SDK would be for applications that needed to do their own NLP.

If that is contrary to your understanding then I can try to find references.

My point here being that supporting Home via API.AI might be more important then supporting it via the actions SDK.

**Comment by jkelvie** [comment]
I agree....we have gotten the same guidance.

Our initial work has been to support this via making logging easy to work with for Express.js on Node. Our assumption is that will be a popular platform for Action building. How does that strike you? You can see the initial WIP here: 
https://github.com/bespoken/bst/pull/190

It is trickier, though, as Google offers less guidance on HOW developers should build their Actions (i.e., they are not pushing something akin Lambdas like Amazon). So I expect we will see a broader array of approaches than with Alexa.

**Comment by GitTom** [comment]
I'm not using Express myself.  When I looked at the actions SDK the Express dependency seemed quite unnecessary (extra fluff) to me so I just used the HTTPS module and emulated the tiny bits of Express that the SDK required.

I can't comment on your logging work.  I'm just using the 'debug' module and viewing output in CloudWatch (which gives me ability to get alerts too).  Where useful I log events and responses to dynamo.  This solution has seemed satisfactory.

What brought me to BST is BSTAlexa which appears to be really great - I'm not aware of any other way of doing proper testing.

**Comment by jkelvie** [comment]
Okay, that's helpful to know. I have another approach in mind for working with the raw HTTP server.

And you might check out our website here for more info on what we are doing with Logless:
https://bespoken.tools/logless

Any feedback on it (what's useful, what's not, what would make it more useful, etc.) is certainly appreciated.

**Comment by GitTom** [comment]
Will take a look and get back to you.
