### ISSUE TITLE
Make sure bst works with yarn

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#178]

**Comment by jperata** [comment]
Adding some detail about current yarn run when bst is not installed 

> 
> yarn global add bespoken-tools
> yarn global v0.22.0
> [1/4] 🔍  Resolving packages...
> warning bespoken-tools > wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
> [2/4] 🚚  Fetching packages...
> error bespoken-tools@0.9.33: The engine "node" is incompatible with this module. Expected version "4.3.2".
> error Found incompatible module
> info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by jperata** [comment]
Issue exist because our current config , indicates that we run only on Node: 4.3.2
  "engines": {
    "node": "4.3.2"
  },
addressing in the related PR

**Comment by jperata** [comment]
After upgrade engines, yarn works downloading the files, but bash can't not find the bst command after install.

**Comment by jperata** [comment]
according to:
https://github.com/yarnpkg/yarn/issues/1321
This is an open bug for yarn, it can be fixed by the user by adding the yarn bin path to $PATH , but up to our installation part we are set up.
