### ISSUE TITLE
Cant install on Ubuntu 16.02 LTS

### ISSUE THREAD

**Issue by hueboy** [bespoken/bst#183]
i was not able to install the command line tools globally using npm install bespoken-tools --save. I have also tried using sudo but no luck. The installation in both the cases works fine but when run bst all I see is

No command 'bst' found, did you mean:
 Command 'tst' from package 'pvm-examples' (universe)
 Command 'ast' from package 'jruby' (universe)
 Command 'bsf' from package 'code-aster-gui' (universe)
 Command 'rst' from package 'bro-aux' (universe)
 Command 'bts' from package 'devscripts' (main)
 Command 'btt' from package 'blktrace' (universe)
 Command 'bist' from package 'bist' (universe)
 Command 'bat' from package 'bareos-bat' (universe)
 Command 'bat' from package 'bacula-console-qt' (universe)
 Command 'gst' from package 'gnu-smalltalk' (universe)
 Command 'bsh' from package 'bsh' (universe)
bst: command not found

node v4.7.2
npm 2.15.11

**Comment by jkelvie** [comment]
@hueboy Did you install it with the "-g" flag? The command "bst" won't be available from the command-line unless you do.

Installing it locally in a project is for using our API programmatically, as opposed to through the command-line interface.

**Comment by hueboy** [comment]
I did the same. It went through without errors but does complain about the version of npm. Please find below

raghu@raghu-HP-EliteBook-840-G3:~/amazon_alexa$ sudo npm install bespoken-tools -g
[sudo] password for raghu:
npm WARN engine bespoken-tools@0.9.25: wanted: {"node":"4.3.2"} (current: {"node":"4.7.2","npm":"2.15.11"})
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
/home/raghu/.npm-global/bin/bst-server -> /home/raghu/.npm-global/lib/node_modules/bespoken-tools/bin/bst-server.js
/home/raghu/.npm-global/bin/bst -> /home/raghu/.npm-global/lib/node_modules/bespoken-tools/bin/bst.js
bespoken-tools@0.9.25 /home/raghu/.npm-global/lib/node_modules/bespoken-tools
├── uuid@3.0.0
├── wrench@1.5.9
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── properties-reader@0.0.15 (mkdirp@0.3.5)
├── winston@2.3.0 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, async@1.0.0, colors@1.0.3)
├── node-zip@1.1.1 (jszip@2.5.0)
├── request@2.79.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, forever-agent@0.6.1, oauth-sign@0.8.2, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, aws4@1.5.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, qs@6.3.0, combined-stream@1.0.5, mime-types@2.1.13, tough-cookie@2.3.2, form-data@2.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── async@2.1.4 (lodash@4.17.4)
└── aws-sdk@2.7.21 (sax@1.1.5, xml2js@0.4.15, querystring@0.2.0, url@0.10.3, jmespath@0.15.0, buffer@4.9.1, crypto-browserify@1.0.9, xmlbuilder@2.6.2<mailto:xmlbuilder@2.6.2>)


Regards,
Raghu Kona

Software Application Engineer - Smart Home (R&D Home Systems Americas)
[hue-transparant-logo]
Innovation, Philips Lighting
Mobile:+1 (503) 954 5563<tel:%2B1%20%28503%29%20954%205563>
https://www.linkedin.com/in/raghukona

**Comment by jkelvie** [comment]
Great, thanks for updating us. Can you run bst commands after installing using -g? Or are you still getting the error "No bst command found"?

**Comment by hueboy** [comment]
I am still getting the error.

Regards,
Raghu Kona

Software Application Engineer - Smart Home (R&D Home Systems Americas)
[hue-transparant-logo]
Innovation, Philips Lighting
Mobile:+1 (503) 954 5563<tel:%2B1%20%28503%29%20954%205563>
https://www.linkedin.com/in/raghukona

**Comment by OpenDog** [comment]
Raghu,

I just fired up a 16.04. I use nvm to manage node versions.

I did this:

1. curl https://raw.githubusercontent.com/creationix/nvm/v0.25.0/install.sh | bash
2. logout/login to get the shell variables
3. nvm install 6.3
4. nvm use 6.3
5. npm install bespoken-tools -g 
6. bst proxy http 3000

Can you try it?

**Comment by hueboy** [comment]
Sorry for the delay. Now I got into EACCESS: permission denied error when I ran

$npm install bespoken-tools –g

Should I try running it with sudo?

Regards,
Raghu Kona

Software Application Engineer - Smart Home (R&D Home Systems Americas)
[hue-transparant-logo]
Innovation, Philips Lighting
Mobile:+1 (503) 954 5563<tel:%2B1%20%28503%29%20954%205563>
https://www.linkedin.com/in/raghukona

**Comment by OpenDog** [comment]
Now you are bumping into the old (non nvm install) I assume. What is the path of npm? 
What does "type npm" command say?

**Comment by hueboy** [comment]
+ Personal Email

Regards,
Raghu Kona

Software Application Engineer - Smart Home (R&D Home Systems Americas)
[hue-transparant-logo]
Innovation, Philips Lighting
Mobile:+1 (503) 954 5563<tel:%2B1%20%28503%29%20954%205563>
https://www.linkedin.com/in/raghukona

**Comment by hueboy** [comment]
raghu@raghu-HP-EliteBook-840-G3:~$ type npm
npm is hashed (/home/raghu/.nvm/versions/node/v6.3.1/bin/npm)


Shall I remove all node, npm and start from scratch with nvm?

Thanks & Regards,

Raghu Kona
Software Application Engineer - Smart Home (R&D Home Systems Americas)

Innovation, Philips Lighting
Mobile: +1 (503) 954 5563

**Comment by jkelvie** [comment]
@hueboy You can talk to us [gitter also](https://gitter.im/bespoken/bst). That can be quicker for these conversations.

**Comment by OpenDog** [comment]
Yes, I would think so. I hope you don't blame if that doesn't fix it... :-) Either way we will figure it out.

-B

**Comment by jkelvie** [comment]
Closing as this was resolved based on discussion in gitter.
