### ISSUE TITLE
Minor docs issue - confusion between BSTAlexa.start and .initialize

### ISSUE THREAD

**Issue by GitTom** [bespoken/bst#187]
[Here](http://docs.bespoken.tools/en/latest/api/index.html) it uses alex.initialize, where alexa is BSTAlexa instance.

But in sample code for BSTAlexa is uses start().

BSTAlexa.initialize is not documented, so I'm guessing it was replaced by start.

**Comment by jkelvie** [comment]
Hi @GitTom, thanks for sending this....fixing in the latest version of the docs.

**Comment by jkelvie** [comment]
Resolved with #190
