### ISSUE TITLE
Minor docs issue - mention slot form for BSTAlexa.spoken

### ISSUE THREAD

**Issue by GitTom** [bespoken/bst#189]
I tried to use BSTAlexa.spoken based on what I read in docs for BSTAlexa, eg.  

http://docs.bespoken.tools/en/latest/api/index.html  
http://docs.bespoken.tools/en/latest/api/classes/bstalexa.html#spoken  

But I couldn't get it working because I wasn't using your slot form, eg.  "my name is {name}".  I figured it out when I came across your 'bst speak' command and read about the slot form of the command in its docs here:  
http://docs.bespoken.tools/en/latest/commands/speak/

I suggest that you note the 'slot form' of the command somewhere here:  
http://docs.bespoken.tools/en/latest/api/classes/bstalexa.html#spoken

Thanks.

**Comment by jkelvie** [comment]
Hi @GitTom....more great feedback. This will be updated shortly as well.

**Comment by jkelvie** [comment]
Resolved with #190
