### ISSUE TITLE
BST with Smart Home Skills

### ISSUE THREAD

**Issue by Dark3nz0** [bespoken/bst#204]
Im loving bst tools, but so far Im not exactly sure how to use the proxy server with a lambda that uses SmartHome Skills? handler on those doesnt have intents. Is it posible to use bst proxy with a smarthome skill? And if so, can you point me in right direction?

**Comment by jkelvie** [comment]
Hi @Dark3nz0 glad to hear it - love the request and we will look into it.

**Comment by jkelvie** [comment]
Hi @Dark3nz0 I added a project that shows how this can be done:
https://github.com/bespoken/lambda-passthru

The short summary is that you need to use a Lambda (because that is all that is allowed with Smart Home Skills) that will pass the data onto our https://proxy.bespoken.tools endpoint. That in turn will forward it to your laptop.

Hope that makes sense - take a look, and let me know if this helps you!

**Comment by NovaGL** [comment]
Can you do this with a custom skill or would you then need to create an intent for each action as that's what i'm currently doing

**Comment by jkelvie** [comment]
Hi @NovaGL for custom skills (not smart home skills) you do not need to use the Lambda Passthru to work with us. You can instead configure the proxy to work directly with your skill. Does that make sense? Am I answering your question?

**Comment by NovaGL** [comment]
What I meant is can a custom skill be a home skill?

Also how can we test a daily briefing?

**Comment by jkelvie** [comment]
A custom skill cannot be a home skill....they have their own unique API.

A daily briefing is a URL that is a JSON file or RSS feed, so that is possible to test with our tools. What in particular are you interested in testing with it?

**Comment by NovaGL** [comment]
Daily briefing I want to add local news and weather.

I could provide my own custom JSON.

Could the daily briefing work with your service that converts mp3s?

Thanks

**Comment by jkelvie** [comment]
Hi, our encoder encodes to a different kbps than what the Flash Briefing requires. Depending on your content source, it may already be in the correct format - 256 kbps MP3. Alternatively, you can had encode it to 256 using Audacity or ffmpeg. Would that work for you? Or do you need on-the-fly encoding?

**Comment by NovaGL** [comment]
Don't worry can use Alexa voice. So how would I do the json can I just use the proxy? Or does flash briefing need to be different

**Comment by jkelvie** [comment]
The Flash Briefing has a simple format based on RSS feeds, which is the standard format for podcast metadata. More info on it [here](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/flash-briefing-skill-api-feed-reference). It uses GET requests, which we do not currently support with the our proxy, but I think you will have an easy time putting your own together. Hope that helps.

**Comment by NovaGL** [comment]
Thanks I can use the Proxy to do a POST to my local server which redirects to a GET.

But the question is would that work or does Alexa have to make the GET command.

**Comment by jkelvie** [comment]
I understand.....we are working on supporting this #253 - we will let you know as soon as it is available.

**Comment by jkelvie** [comment]
We added support for all HTTP verbs some time ago
