### ISSUE TITLE
Logless Middleware & Types from @types/express

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/bst#207]
When installing the express type definitions using:

```
$npm install @types/express
```

I get a compile error in logless.d.ts when I attempt to convert from TS to JS:

```
ERROR in /Users/michaelmyers/Desktop/mortgage/node_modules/bespoken-tools/lib/logless/logless.d.ts
(1,32): error TS2307: Cannot find module '~express/lib/router/index'.

ERROR in /Users/michaelmyers/Desktop/mortgage/node_modules/bespoken-tools/lib/logless/logless.d.ts
(2,30): error TS2307: Cannot find module '~express/lib/express'.
```

If I use the same type definitions in the BST project, it works:

```
  "dependencies": {
    "express": "registry:npm/express#4.14.0+20160925001530"
  }
```
This is most likely a discrepancy between the definition files.

**Comment by michaelmyers** [comment]
I am using 0.9.30.  This screenshot shows the version and the error:

<img width="1280" alt="screen shot 2017-03-02 at 12 16 53 pm" src="https://cloud.githubusercontent.com/assets/921356/23518664/31989d1e-ff42-11e6-8449-3cb17f778005.png">

**Comment by OpenDog** [comment]
You need this in your typings dependency:

   "express": "registry:npm/express#4.14.0+20170217205433"

Then typings install.

**Comment by jkelvie** [comment]
Yes, but that should not necessary. 

Even though I removed the dependency from the code in version 0.9.30, it did not get pushed properly to npm. I'm fixing that now.

**Comment by OpenDog** [comment]
Can you make the method "logger" public (the "raw" logless context)? I'm using it in the xp server.

**Comment by michaelmyers** [comment]
Yes. I did get it working using that however since @types is the new way to [install](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) definition files, I tried to use it. DefinatelyTyped now [recommends](https://github.com/DefinitelyTyped/DefinitelyTyped#npm) installing @types.

**Comment by jkelvie** [comment]
There is a version 0.9.31 that is available now as a beta - need to explicitly specify it in package.json. It should resolve the issue. Please give it a try.

**Comment by michaelmyers** [comment]
0.9.31 resolves the issue.  I am installing with @types and no longer getting the error.
