### ISSUE TITLE
Create spoke first time bst is used

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#212]

**Comment by jkelvie** [comment]
The first time someone launches the proxy, it should create a new spoke for them.

To create a spoke, it should get a unique name for it, by calling the sourceNameGenerator service:
https://github.com/bespoken/source-name-generator

See the /v1/sourceID endpoint. It should be called WITHOUT an id so that it randomly generates one.

With that sourceID name, the Spoke API should be called:
https://docs.google.com/document/d/1CtY5DBAxDfbGXDwioYs4xqQRHmYF4uGiQfMPlUy-29s/edit#heading=h.c7kmxfq4g8kk

The Save Pipe endpoint should be called - /pipe.

The fields should be set in this way:
UUID - Generated UUID for the bst client (the node ID)
diagnosticsKey - null
endPoint.name - The generated Source ID
http.url - https://proxy.bespoken.tools?node-id=<NODE_ID>
path - "/"
pipeType - HTTP
proxy - true

The result of all this is a new URL will be created that the bst user can interact with to proxy data.

This URL will accept data and then forward it to the bst server. By passing all the data through this URL first, we can show it in the dashboard as soon as the user signs up.

**Comment by jperata** [comment]
Reopened because there was some parameters set up incorrectly.
