### ISSUE TITLE
Logless: Adding origin of log

### ISSUE THREAD

**Issue by chrsdietz** [bespoken/bst#215]
The payload received to the Logless server comes in this form:

```
{
    "source": <source_key>,
    "transaction_id": <uuid>,
    "logs": [{
        "payload": <request_payload>,
        "tags": ["Request"],
        "timestamp": <timestamp>,
        "log_type": <INFO, ERROR, DEBUG, ETC.>
    }, {
        "payload": "A message that corresponds with the log.,
        "tags": [],
        "timestamp": <timestamp>,
        "log_type": <INFO, ERROR, DEBUG, ETC.>
    }, {
        "payload": <response_payload>,
        "tags": ["Response"],
        "timestamp": <timestamp>,
        "log_type": <INFO, ERROR, DEBUG, ETC.>
    },]
}
```

This appears to come from the Logless utility in BST.  For a while, it has determined based on the payload provided what kind of log it is, but the issue comes with the middle type logs in which there are no payload. Is it possible to put an origin "Amazon.Alexa" or "Google.Home" in the payload?

**Comment by jkelvie** [comment]
The way to resolve this to add a source_type field with values AMAZON_ALEXA, GOOGLE_HOME and UNSPECIFIED on the top level of the JSON.
