### ISSUE TITLE
Ability to turn of logging to console in BSTAlexa & LambdaServer

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/bst#225]
I am using BSTAlexa and LambdaServer for running automated tests, I would like a way to turn off all outputs from these classes so my console is clean and I can more easily track the tests.

**Comment by michaelmyers** [comment]
Still seeing a couple of logs in version 0.9.35:
```
info: BST-LAMBDA  LambdaServer started on port: 10000
Intent: LiveStreamIntent Session: [object Object]
info: ALEXA       CALLING: IntentRequest
```
Can these be turned off or is this intentional?

**Comment by jkelvie** [comment]
The Intent statement should definitely be gone, so not sure what is happening:
https://github.com/bespoken/bst/commit/a8c13f862f37ae44de6870fa1deeefefcedf35f8

Are you definitely on 0.9.35?

**Comment by michaelmyers** [comment]
First time I installed I used `yarn install`, which looks like it errored out and I didn't notice.  I switched over the verbosity and noticed the request/responses went away, which is why I thought the install worked.

Just installed with `npm install` and yes, it updated the version.   The logs are clean.  Thank you.
