### ISSUE TITLE
Not sure if winston is working as intended with BST?

### ISSUE THREAD

**Issue by tylerhslee** [bespoken/bst#242]
To reproduce, you need to force the `Reloading` log from `bst proxy` by changing a file while the server is running. I encountered this while testing my skill with a local DynamoDB server up, because the `shared-local-instance.db` file changes whenever I alter the database. (It seems that the Reloading log isn't always triggered by _any_ file changes)

Basically, if I create a new `winston` logger of my own with a file transport and import it to the Mocha test file, the `Reloading` log prints out to the stdout along with all the request/response JSON, clogging the screen and making it difficult to read the output. However, if I don't import the logger at all but still have the separate `js` file that contains the configurations, the logs are correctly logged to the defined file path. When I do _not_ have `redirect.js` at all, the logs are put on stdout.

Below is what my files look like when BST _does_ log to stdout no matter what file path I give to the transports.

**index.js**
```javascript
"use strict";

const Alexa = require("alexa-sdk");
setupDynamo();

exports.handler = function (event, context, callback) {
    const alexa = Alexa.handler(event, context);
    alexa.dynamoDBTableName = "HelloWorld";
    // ...
}

function setupDynamo (alexa) {
    // AWS configs
}
```

**test/Alexa.js**  
```javascript
"use strict";

const logger = require("./redirect");

describe("Sample", function () {
    it("Does something to the DB", function (done) {
        // do something
    });
    done();
});
````

**test/redirect.js**
```javascript
"use strict";

const winston = require("winston");

winston.configure({
    transports: [
        new winston.transports.File({
            filename: "log/bst.log",
            handleExceptions: true,
            json: false
        })
    ]
});

module.exports = winston
```

I have tried creating a whole new `Logger` object without messing with `winston`'s global config, but the problem still persists. Putting `winston.remove(winston.transports.Console)` didn't help either. I don't know if this is intended behavior of `winston`, but it seemed odd that simply importing the object and/or even creating a whole new object can affect the way BST interacts with `winston`.

I am aware of my options with Logless (which I am using right now), but I'd still love to make `winston` work. Just a bit stubborn of me I guess :^)

**Comment by jkelvie** [comment]
Closed as we do not plan address in the near-term
