### ISSUE TITLE
bst config error

### ISSUE THREAD

**Issue by vallamk** [bespoken/bst#249]
Hi,

I am trying to set up BST tools on my mac laptop.
I started with this "Getting Started" document.
http://docs.bespoken.tools/en/latest/getting_started/#updating

and installed bespoken-tools with npm.
using "sudo npm install bespoken-tools -g"
Install was successful.

Then i tried to test bst,
$ bst

i am getting the below error

BST: v0.9.37  Node: v7.8.0

INFO  2017-05-01T21:26:54.003Z No configuration. Creating one: /Users/XXXX/.bst/config
ERROR 2017-05-01T21:26:55.681Z 
	{"message":"Cannot read property 'name' of undefined","stack":"TypeError: Cannot read property 'name' of undefined\n    at Function.<anonymous> (/usr/local/lib/node_modules/bespoken-tools/lib/client/bst-config.js:96:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/local/lib/node_modules/bespoken-tools/lib/client/bst-config.js:4:58)\n    at process._tickCallback (internal/process/next_tick.js:109:7)"}

Any help is greatly appreciated.

**Comment by falent** [comment]
I wasted one day for finding the solution :D

try:
sudo npm install bespoken-tools@0.9.35 -g

After that it should work! I think current version has a bug.

**Comment by vallamk** [comment]
Thankyou so much Falent for quick response. You saved my day.
I hope this issue will be fixed soon in the current version.

**Comment by jkelvie** [comment]
Hi @vallamk thank you for reporting this - sorry that you had to deal with this. We are actively working on a fix now, and will let you all know as soon as it is available.

And @falent thank you for suggesting the workaround :-) We have rolled back the main npm version to 0.9.35 for everyone so they don't need to wrestle with this.

**Comment by jkelvie** [comment]
Hi @vallamk and @falent, this issue has been resolved in the latest version. Thank you for reporting it to us!
