### ISSUE TITLE
Create mock config for unit tests

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#260]
Outside of the config tests, we do not need to run the config.load() over and over. It slows down the tests and causes errors.

One idea would be to use an environment variable to trigger the mock. The environment variable can be set as part of the Run/Debug template inside webstorm. It can also be set in .travis.yml.

In that way, we can ensure running tests locally as well as in Travis uses the mock, but elsewhere it will use the real thing consistently.

**Comment by jperata** [comment]
We removed all references to external webs by internal mocks during testing, so right now no new sources are created.
