### ISSUE TITLE
Improve how we generate Typescript definition for bst library

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#261]
Currently, we rely on the compilerOptions.declaration = true to generate the index.d.ts file for use by people using our library as typescript programmatically.

This flag causes "d.ts" files to be created for every file in the project, which is not what we want. Ideally, we would have single index.d.ts that contains the actual definitions we want to export, not just links to definitions (as with the current index.d.ts).

The overall idea is that we want a clean declarations file that exposes everything we want people to use, but does not expose private stuff and things we do not want people to use.

Potential solution:
https://github.com/rsms/tspkg

Previously had looked at this:
https://github.com/SitePen/dts-generator
I had issues with dts-generator, I believe due to how it relied on modules.

In general, this is a tricky problem. Hopefully either TypeScript will provide a better solution, or one of the third-party packages will work better.

**Comment by breathe** [comment]
What is the reason not to simply turn off declarations and rename index.ts to index.d.ts?

**Comment by jkelvie** [comment]
That was my initial approach. I am trying to remember the issue I had with it - I believe it was that it would create a cascade of dependencies - as just exporting the classes themselves, as opposed to their declarations, would end up requiring all the libraries they used. And without the additional typescript dependencies for these libraries in the including project, it would error out on when compiling.

Perhaps this could be skirted by adding the TypeScript definitions to the dependencies, though that seems a bit heavyweight.
