### ISSUE TITLE
Spoken command does not work correctly with literals

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#266]
Sample utterances for literals contain sample slot values, such as this:
SearchByName {John|nameToSearch}

We need to correctly parse out that `nameToSearch` is the slot name, and ignore John, which is a hint for the Alexa NLU.

When someone uses the spoken call with a literal, it incorrectly tries to match the slot on the intent with the value "John|nameToSearch", when it should do the lookups in the interaction model with just "nameToSearch".

**Comment by jkelvie** [comment]
Reported by @michaelize

**Comment by jperata** [comment]
Closed as current version
