### ISSUE TITLE
Add support for new intent schema/utterance structure

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#269]
The new Skill Builder introduces a new consolidated intent schema, that puts the sample utterances and intents together.

BST should be updated to support this.

**Comment by mark695073649** [comment]
any update on this?

**Comment by jkelvie** [comment]
Hi @mark695073649 - quick question - were you looking to use bst for unit-testing, or for the CLI commands? Or both? We have a new project, https://github.com/bespoken/virtual-alexa that now supports the new interaction model for unit-testing.

And we will soon be retro-fitting our CLI to use this as well.

**Comment by mark695073649** [comment]
Hi @jkelvie , I'm looking for both. Thx, this is awsome.

**Comment by jkelvie** [comment]
Okay, it is in the virtual-alexa project....I'm going to update this issue again once it is added to the command-line. Then we will close this :-)

**Comment by nixonad** [comment]
Hi @jkelvie,
It seems Virtual-Alexa doesn't support the exact same format of the interaction model as the designer. The tests in the virtual-alexa project target two file formats, neither of which is exactly the same as the one copied from the interaction designer. It's close to the SMAPI format you have, but that file includes a "interactionModel" element at the top level of the file which is not in the file from Amazon's site.
Is this something you are aware of? plan to change or not?
Thanks

**Comment by jkelvie** [comment]
Hi @nixonad - we support three formats:
1) "Classic" IntentModel.json and SampleUtterances.txt - the original format
2) InteractionModelV1 - format created in the Interaction Model builder in the developer console
3) InteractionModelV2 - format created via ASK CLI and support via SMAPI

The main difference between V1 and V2 being that what was the interaction model in V1 now sits under the path "interactionModel.languageModel".

There is a test for this here:
https://github.com/bespoken/virtual-alexa/blob/master/test/VirtualAlexaTest.ts#L16

The JSON structure for that test is here:
https://github.com/bespoken/virtual-alexa/blob/master/test/resources/InteractionModelSMAPI.json#L2

```
{
  "interactionModel": {
    "languageModel": {
      "intents": [
        {
          "name": "TellMeMoreIntent",
          "samples": [
            "contact info",
            "tell me more",
            "more details"
          ],
          "slots": []
        }
      ]
    }
  }
}
```

Can you tell me more about the specific issue you encountering, and the file structure and contents?

**Comment by nixonad** [comment]
@jkelvie Thanks for the reply. I wasn't using the ASK CLI. The file that I can manually access on the ASK website looks like this:
```
{
  "languageModel": {
    "intents": [
     ]
  }
}
```
while the one retrieved via the CLI looks like your format:
```
{
  "interactionModel": {
    "languageModel": {
      "intents": [
       ]
    }
  }
}
```

Using the CLI obviously makes more sense anyway so I'm sorted.
Thanks!

**Comment by jkelvie** [comment]
So, it appears that they have add a fourth version, which is that the interaction model builder now outputs a language model element at the top-level.

I will add some code to support this scenario as well. This is the version that Amazon was originally producing via the interaction model builder:
https://github.com/alexa/skill-sample-nodejs-hello-world/blob/master/speechAssets/interaction-model.json

All that said, using the ASK/SMAPI version I believe is the best approach, as Amazon is converting all their examples over to it.

**Comment by jkelvie** [comment]
Just a quick update - I made changes to support the "new" interaction model builder format.

They are part of Virtual Alexa - you can see them here:
https://github.com/bespoken/virtual-alexa/commit/7c7dc7851a8c0e6504885a9a5bcf9e293cc1ab34

Additionally, they are part of the 0.3.8 npm release.

Thanks for bringing this to our attention!

Best,
John

**Comment by nixonad** [comment]
Excellent!, thanks for the update, and for awesome tools :-)

**Comment by jkelvie** [comment]
Accidentally closed - forgot that I am going to provide an update once this is integrated into the command-line. Should be soon - then will close.

**Comment by CoreyCole** [comment]
@jkelvie I'm on the latest bespoken-tools 1.2.9 and my `intent-schema.js` file has having trouble passing the intent name to the Intent constructor. I fixed this by changing:
```javascript
let intent = new Intent(intentJSON.intent);
```
to
```javascript 
let intent = new Intent(intentJSON.intent || intentJSON.name);
```

**Comment by CoreyCole** [comment]
It was also having trouble finding the intents array inside of the object created by the developer console. To make that work, I chopped down my intents file from something like this:
```json
{
    "interactionModel": {
        "languageModel": {
            "invocationName": "test name",
            "intents": [
```
to this
```json
{
    "intents": [
```

**Comment by jkelvie** [comment]
Hi @CoreyCole can you tell me a bit more about what you are trying to do? Without knowing exactly, it looks like you are trying to work with our emulator programmatically, in which case you should generally use this:
https://github.com/bespoken/virtual-alexa

This supports the new interaction model without issue.

Best,
John

**Comment by CoreyCole** [comment]
Ah, sorry I'm new to the bespoken tools ecosystem. I'm setting up an integration test pipeline for a typescript project using jest for snapshot testing. So I was setting up my tests like this:
```javascript
    beforeEach((done: jest.DoneCallback) => {
        // the below file paths are relative to where package.json is for some reason
        // maybe because it's where the test command is called...
        server = new bst.LambdaServer('./init.test.ts', 10000, true);
        alexa = new bst.BSTAlexa('http://localhost:10000?disableSignatureCheck=true',
            './speechAssets/IntentSchema.json',
            './speechAssets/SampleUtterances.txt',
            constants.appId);
        server.start(() => {
            alexa.start((error) => {
                if (error !== undefined) {
                    console.error(`Error = ${error}`);
                    done();
                } else {
                    done();
                }
            });
        });
    });
```

So looks like I don't need to be using the bst package for this? The `bst.LambdaServer` is not required anymore? i.e.
```javascript
    beforeEach((done: jest.DoneCallback) => {
        alexa = va.VirtualAlexaBuilder()
            .handler('index.handler')
            .intentSchemaFile('./speechAssets/IntentSchema.json')
            .sampleUtterancesFile('./speechAssets/SampleUtterances.txt')
            .create();
    });

    afterEach((done: jest.DoneCallback) => {
        // not needed ?
    });
```

**Comment by CoreyCole** [comment]
@jkelvie I'm running into a new issue opened over in the va repo: https://github.com/bespoken/virtual-alexa/issues/46

**Comment by jkelvie** [comment]
Closing this as the original issue is resolved.
