### ISSUE TITLE
$bst proxy urlgen Command Make alexa-url Argument Optional

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/bst#27]
For lambda based skills or new skills, a service endpoint may never exist or doesn't exist currently.  

When generating the url using `$bst proxy urlgen`, there is nothing to pass for the second required argument `alexa-url`.  Right now you just have to pass a dummy URL.

I recommend to either make it optional or remove it all together since the only thing that is actually required is the `node-id`.

**Comment by jperata** [comment]
bst proxy urlgen was removed, now the url are printed on proxy usage
