### ISSUE TITLE
parameters in command

### ISSUE THREAD

**Issue by NovaGL** [bespoken/bst#283]
How do I send a parameter for example I want to look up a TV show.

I would say alexa ask tv show "suits". how do I pass the word suits to then get the custom response

**Comment by jperata** [comment]
Hi,
if the tv show is declared as a slot, you can surround it to specify it. You can check that in more detail here:

http://docs.bespoken.tools/en/latest/commands/speak/#working-with-slots

But for your specific example it should be:

$ bst speak ask tv show {suits}

**Comment by NovaGL** [comment]
Thanks will give it a go. So slots are dynamic or only predefined values as there are thousands of shows.

**Comment by jperata** [comment]
Amazon have predefined values , one of them is actually [tv series](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/slot-type-reference#tvseries),  you can also add you're own list if you find it is not sufficiently updated.

**Comment by NovaGL** [comment]
Awesome! Will let you know how I go. Just figured out OAuth for Trakt.tv so this should be fun

**Comment by NovaGL** [comment]
Can I just do it with Proxy or does it need something else. I cant see the word in testing

**Comment by NovaGL** [comment]
Figured it out it was "AMAZON.SearchAction<object@CreativeWork"

My next problem will be how to filter out the other info that gets put in the slot.

The beta builder was the answer couldn't find the answer any other way.

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/videocreativework-intents

**Comment by NovaGL** [comment]
All working 👍 

http://i.imgur.com/cotxk1C.png

**Comment by jkelvie** [comment]
Glad to hear it, thanks for the update @NovaGL
