### ISSUE TITLE
Running 'speak' agains a lambda function without proxy

### ISSUE THREAD

**Issue by feedm3** [bespoken/bst#284]
Is it possible to run the `speak` command directly against a lambda function where my skill is deployed?

Example command:
```
bst speak open test skill --url arn:aws:lambda:eu-west-1:1212132:function:alexa-skill-test
```

**Comment by jkelvie** [comment]
Hi Fabian, that is a great request.

At this moment, the answer is no, but I'm going to leave this open as we are working on something that will allow for this - I will update you once it is ready.

**Comment by jkelvie** [comment]
Hi Fabian, please take a look at this issue that we added:
#359 

This will accomplish what you are looking for I believe - I will ping you again once it is completed and ready.

**Comment by jkelvie** [comment]
Hi @feedm3 - we have released our updated speak command - you can read about it here:
https://bespoken.io/blog/the-new-improved-speak-command-for-testing-alexa-skills/

Please give it a try, and let us know what you think - feedback is greatly appreciated.
