### ISSUE TITLE
Different action per physical echo

### ISSUE THREAD

**Issue by NovaGL** [bespoken/bst#291]
This might be a simple question but don't have internet to my Echo dot to test.

Scenario.

Alexa "Ask room what's the temperature"

Bedroom Dot - "It's 22C in the Bedroom"
Kitchen Dot - "It's 18C in the Kitchen"

Each Echo would have it's own ID right?

So when the skill is sent to Echo and through to BST it passes the ID?

I would rather program in the ID of each Echo into my app than to  say "ask room whats the temperature in bedroom."

My devices aren't compatible with Alexa so can't do it naively. 

Let me know if this makes sense or if you need further information.

I hope to have internet again in the next few weeks to test out.

**Comment by NovaGL** [comment]
I think what I am looking for is amzn1.ask.device?

Is this the best way to determine the device?

**Comment by jperata** [comment]
yes, the device id ( context.System.device.deviceId ) will remain unique for the app, you can ask the user to save those with a name and save it. 
Remember though that this id's will change if the user disable the skill and the enable it again.

**Comment by NovaGL** [comment]
I should have time to test this on the weekend will let you know how it goes.

Going to setup "Goodnight" So it will overide her default action and turn of all the lights  and AV equipment in the current room instead.
