### ISSUE TITLE
Support for Echo Show

### ISSUE THREAD

**Issue by NovaGL** [bespoken/bst#304]
I noticed that design guidelines have changes. 
Will BST support these new changes to make cards for Echo Show. I don't have one to test out.

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/display-interface-reference

**Comment by jkelvie** [comment]
We are supporting the show for unit-testing with our virtual-alexa project. You can read about it here:
https://github.com/bespoken/virtual-alexa/blob/master/docs/Display.md
