### ISSUE TITLE
Capture errors in bst-debug.log

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#306]
If the bst has errors, we should capture the detailed output into bst-debug.log in the local directory where the user is running it.

We can then ask them to send it to us for help in diagnosing issues.

Information should include entire stack trace of exception, plus any message associated with an error.

**Comment by jperata** [comment]
Will setup so that error logs stack in the file instead of replacing each time, plus a timestamp so we can see if it correspond to an outage or something.
