### ISSUE TITLE
new Smart Home control

### ISSUE THREAD

**Issue by NovaGL** [bespoken/bst#314]
Hi,

Can you explain how this might work with BST. Eg to control a Sonos or TV

https://developer.amazon.com/blogs/alexa/post/78f44d51-5bdf-4a4c-8eaa-57d1282c8212/introducing-entertainment-capabilities-in-alexa-smart-home-new-device-controls-for-tvs-av-receivers-and-ir-hubs

**Comment by jkelvie** [comment]
Hi, our lambda pass-thru approach, similar to other Smart Home skills should still work, as discussed here:
https://github.com/bespoken/bst/issues/204

The Lambda passthru code is available here:
https://github.com/bespoken/lambda-passthru

The passthru is necessary as Smart Home skills only work with Lambdas - so to get at the data, we need it to be forwarded to our proxy.

Does that make sense? Let me know your thoughts and questions.

**Comment by NovaGL** [comment]
Thanks, could you maybe make a blog post or something with an example of it working?

**Comment by jkelvie** [comment]
Hi yes, that is a good suggestion....we will add something for that. We are also just generally thinking about ways to help Smart Home dev.

**Comment by NovaGL** [comment]
Since pass through repo is gone is there any other way to test smart home skills?

**Comment by jperata** [comment]
We have published a blog post on our approach to smart home skills
https://bespoken.io/blog/smart-home-test-automation-for-alexa/

along with a sample repository on the approach
https://github.com/bespoken-samples/smart-home-skill-testing
