### ISSUE TITLE
Statistics not being captured correctly

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#325]
Since we switched over to Hyper, the bst-stats table is no longer being populated.

There are no errors in the logs, and the debug messages in the hyper logs indicate things are working correctly, but no data is captured.

Additionally, it seems that we are still using old keys and environment. We should switch to new keys and environment. I can explain further.

**Comment by jperata** [comment]
this needs two steps: 
1) update credentials so bst server starts writing to correct environment again.
2) migrate stats that went into the other environment.
