### ISSUE TITLE
Howto: BST with IFTTT

### ISSUE THREAD

**Issue by NovaGL** [bespoken/bst#328]
Delete if not appropriate.

I thought it might be nice to mention in the readme that this service can work with IFTTT.

I was trying to setup with API. AI and found it to difficult.

Google Assistant works really well with IFTTT.

Simply putting your bst proxy url in the webhook field for IFTTT allows for easy operation with not much work.

HTTP POST works well as you can include in your payload the command you want to do. I do validation so only the correct message goes through to the destination.

Curious to know thoughts

**Comment by jkelvie** [comment]
Hi, to make sure I understand - you are calling Google Assistant from IFTTT? What Google Assistant API are you using?

**Comment by NovaGL** [comment]
IFTTT has it's own API. It uses that. You can also use it with Alexa but then you would have to say "trigger"

![IFTTT](http://i.imgur.com/9LFUStk.png)

**Comment by jkelvie** [comment]
Are you using the proxy with IFTTT to trigger actions locally on your machine? Just trying to make sure I understand.

**Comment by NovaGL** [comment]
Yes, that is correct. Is that no something you foresee this project being used for?

**Comment by jkelvie** [comment]
I think it's an interesting use-case, even if it's not the original one we had in mind. It's close enough to the current functionality that I believe it is worth supporting.

The two main issues I see with how we do this today, aside from documentation:
1) Security issues with persisting tunnels for long periods
These are something to consider regardless, but to me take on greater importance if the tunnels are meant to be durable. A tunnel that is always available is much more vulnerable to attack than one that is only available intermittently, and potentially pointing at different services each time.

Nevertheless, I think those concerns are best addressed in the other issue you opened though, so I won't comment on that further here. (https://github.com/bespoken/bst/issues/332)

2) Durability of tunnels
The proxy is built to "give up" after certain number of network failures. In this scenario, with a reasonable backoff, I think it should persist indefinitely trying to reconnect in the case of network outages.

Have you run into any other issues with keeping the tunnels alive for long periods?

**Comment by NovaGL** [comment]
No issues here. I use PM2 so even if it fails it reconnects.

I really want to know your comments on security so look forward to reading your thoughts in the other thread

**Comment by jkelvie** [comment]
Closed as we clean up issues - we have no more plans regarding this one.
