### ISSUE TITLE
Logger doesn't output error backtraces

### ISSUE THREAD

**Issue by Ravenstine** [bespoken/bst#345]
Things like `TypeError: Cannot read property 'undefined' of undefined` aren't very helpful if there's no backtrace or line number.  I see no mention of this anywhere.  Is there a way I can also have errors display a backtrace in the logger?

**Comment by jkelvie** [comment]
Hi @Ravenstine - thank you for letting us know. Are you referring to the console output in the dashboard? Or on the command-line?
