### ISSUE TITLE
Generate messages dynamically in BST output

### ISSUE THREAD

**Issue by jperata** [bespoken/bst#357]
#### General changes
1. Recolor the message stating the BST and node versions to green (should look good on different terminal backgrounds).

#### Tips messaging:
1. Have a collection of tips on how to use the different commands from bst ("Did you know?...).
2. Pick one of the messages randomly and show it below the bst and node versions. Also in green.
NOTE: Tip messages should be short and should be shown every time bst is used. Also, we should have the ability to disable specific messages.

#### Custom messaging:
1. Have zero or one messages at a time for promotional stuff. If present or enabled, this kind of messages should go below the tips message. Use the blue color that we use already in bst output when tracing is enabled.

#### Version messaging:
1. Have the latest official version number of bst published somewhere in our API or taken from npm. 
2. Verify from the code of bst if the current version of the installed library is the same as the one published. 
    - If true, we keep the output the same as of now.
    - If not, add a line under the custom message: 
```
Update available <current installed version> --> <current last version>.
Run npm install -g bespoken-tools to update.
```
Example:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/6411740/44365120-72045d00-a48e-11e8-99c7-8dd8a9082c0e.png">

# IMPORTANT 
If retrieving or showing any of the messages causes an error, it should be a silent failure. That is, no exception should be shown on the terminal and the bst commands should continue working.

**Comment by dmarvp** [comment]
Updated the ticket description to better reflect what we want to accomplish here.

**Comment by jkelvie** [comment]
Where will this data come from? In what format will it be specified - for example, how will colors be indicated?

**Comment by jperata** [comment]
- The colors are going to be static. Each section have it's own color.
- The data will come from firebase by they way of source-api in case of the tips and custom messages, is our more easy to update repository and we can assign writing issues to that specific tree.
- In case of the npm update we can use https://www.npmjs.com/package/update-notifier or a similar library to avoid reinventing the wheel for that specific section.

**Comment by ecruzado** [comment]
Can be tested using https://github.com/bespoken/bst/releases/tag/v2.0.16

**Comment by MKen-li** [comment]
Marked as verified
Build = 2.0.17
