### ISSUE TITLE
Updated speak command

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#359]
We want to integrate the Silent Echo into our bst command-line.

To do this, we need to:
1) Re-brand the existing speak command that uses the emulator as "utter"
2) Create a new speak command that uses silent echo

For new the command, it should be defined as follows:
bst speak [options] <complete utterance>

The options are:
>--token The token for interacting with your virtual Alexa device - get it here:
>      https://apps.bespoken.io/dashboard/validation
> (Bespoken Dashboard account required for use of this feature)

The token is saved off to the .bst/config file when entered, so it does not need to be re-entered every time.

The phrase and the token should be used to call the silent-echo-sdk. The result should include:
* The transcript of the output (if present)
* The stream audio URL (if present)
* The card data (if present)

Suggested layout:
> Transcript:
> Welcome to we study billionaires!
>
> Stream:
> https://mystream.com/link.mp3
>
> Card:
> My Card Title
> My Card Subtitle
> My Card Content
> https://mycard.com/image_url

The existing "speak" command should behave the same, though the name should be changed to utter.

**Comment by jperata** [comment]
Flows considered:
 - User use speak without token when token not saved:

> You need a token for this option to work, get it here:
> https://apps.bespoken.io/dashboard/validation
> (Bespoken Dashboard account required for use of this feature)
> Then try again with
>    bst speak --token <ProvidedToken> <Speech to try>

 - Using speak without token when token is already saved:

> Transcript
> ...

- Using speak with token (doesn't matter if it's not saved because we save on this step every time in case user is replacing the token)

> Your token is saved, you can now use this option without providing the token
> Transcript
> ...

**Comment by jkelvie** [comment]
Looks good - I would change the text in the last scenario to say:
> Your token is saved, you can now use this command without providing a token
