### ISSUE TITLE
Enable multi-user support

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#363]
Per this spec:
https://docs.google.com/a/bespoken.tools/presentation/d/169Xzz4ZYHEXxZ3phyZXCwqHQ3lYlJpa-Hxe5E5mqBmI/edit?usp=sharing

**Comment by NovaGL** [comment]
What do you mean multi-user? Obviously I can't access the google doc to know what you mean

**Comment by jkelvie** [comment]
HI @NovaGL I put that in the wrong project - it is a dashboard feature.

If you would like to take a look at it and provide input, I would be happy to give you access. 

The crux of the feature is to allow multiple users to access the same app data via our Dashboard frontend.
