### ISSUE TITLE
Look into speeding up Logless flush time

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#370]
Per email from @OpenDog:
>So here is some constructive criticism.
> Currently the logless flush happens synchronously. In other words it eats up time from the skill's response time. It's pretty decent but the two request calls still cost almost 100 ms. I was wondering if this could happen in an "open ended" async call. In other words you let the skill response go (finish lambda or express call) then you flush the logs asynchronously (If it fails log it). 
> Our Stentor is a lambda skill server, triggered from the AWS API GW, so I'm not sure if Amazon would finish the API GW call before all the async calls finished in the lambda, but in Express this will work. 

Currently, we send the logs partially async:
1) We wait for them to complete sending the request (by waiting on the "end" event)
2) We do not wait on a response

A few things we can try:
1) Remove the wait on the "end" event and see if data is still consistently sent from a llambda
2) Try to find a way to force request data to be flushed without waiting
3) Try sending data asynchronously to another llambda, which in turn will send to the logging server

We should look at each of these options and compare performance times and reliability.

**Comment by OpenDog** [comment]
llambda?

**Comment by jkelvie** [comment]
It's rebranding ;-)

**Comment by OpenDog** [comment]
So it's pronouced "yamda"?

**Comment by jkelvie** [comment]
I was thinking "Lom-da"
