### ISSUE TITLE
Help playing HTTP Podcast

### ISSUE THREAD

**Issue by NovaGL** [bespoken/bst#372]
Hi,

I have tried with streamer but would prefer with pure bst webhook.

How can I get Alexa to play the following podcast
http://www.abc.net.au/radio/programs/news/feed/8353528/podcast.xml

**Comment by jkelvie** [comment]
By pure bst webhook, do you mean you want to play the podcast without hosting it anywhere, neither via lambda nor server?

And in general, configure the streamer to work with a podcast feed, you just set the feed as the environment variable RSS_URL. In this case it would be:
RSS_URL=http://www.abc.net.au/radio/programs/news/feed/8353528/podcast.xml

However, the actual podcasts in the file I see are not available via SSL. It is fairly common that podcast episode URLs are in plain http. There is actually code in the streamer to fix this and change the URL to https. 

For most podcast hosts, that will work. However, these podcasts give a security exception when one tries to load them via https:
https://mpegmedia.abc.net.au/news/audio/google/nbn-2017-08-29-03-00.mp3

I believe that will not work with the Alexa AudioPlayer, which requires a valid HTTPS URL for audio.

**Comment by NovaGL** [comment]
I wanted to use BST Proxy to proxy the mp3 address but not sure how. Thought of a RSS parser but I'm not great with nodejs

**Comment by jkelvie** [comment]
The bst proxy is probably not the best fit for that use-case. You would need to keep it running all the time on your machine, acting as an intermediary between Alexa and the podcast audio. This is a bit of an odd arrangement, though I think technically feasible.

We have production proxies, but I would need to configure it for you (we plan to make those widely available soon, but have not yet). In that case, the data would be proxied through our spokes (our name for our production proxies). You would also need to update the streamer code to automatically replace the URL so that it uses our proxy domain as opposed to the original one.

What do you think?

**Comment by NovaGL** [comment]
I was going to run it in the cloud using glitch.

What would you say is the best way to store the mp3 url in a node variable.

I can get it to show on console log but can't save it

**Comment by jkelvie** [comment]
Gee, that is a neat use of glitch....that opens some interesting possibilities I really had not thought of 🤔 ⚡️.

Even if you are not going to use the streamer, I would recommend at least grabbing the RSS parser from there:
https://github.com/bespoken/streamer/blob/master/lib/rssAdapter.js

It's a pretty basic wrapper around an XML parser - makes life much easier.

Another alternative would be to just use the xml2js library - in that case, the code above is a good cookbook for how to use it with RSS.

**Comment by NovaGL** [comment]
Thanks. Sorry for the novice question but once I parse it. How can I use the result in another function. I know its a dummy question just looking for guidance

**Comment by jkelvie** [comment]
Just return it? Since it's node, it may be async, in which case pass it as a callback, but not much different that any other programming language. If that's not helpful, you can send me the code and I'll take a look (via gitter - https://gitter.im/bespoken/bst - I'm jkelvie).

**Comment by NovaGL** [comment]
Here is the example which will help explain

```
var parser = require("blindparser")
parser.parseURL('http://www.abc.net.au/radio/programs/news/feed/8353528/podcast.xml', function(err, out){
    console.log(out.items[0].media.content.url);
});
```

I want that console out in a variable. I don't know how to.

**Comment by NovaGL** [comment]
I got it working yay!
https://sage-bridge.glitch.me/ABC

I just had things in the wrong order.
