### ISSUE TITLE
Proxy hangs when card content has special character

### ISSUE THREAD

**Issue by onedotover** [bespoken/bst#375]
If the card content has a special character like a ’ it freezes.

**Comment by jkelvie** [comment]
Thanks for the additional info on the bug - we will look into it.

**Comment by jperata** [comment]
@onedotover Hi, was trying to reproduce the issue, but i couldn't. 
If you can provide the response that's being generated or an example emit, i tried with tests like
`this.emit(':tellWithCard', speechOutput, "break `´ attempt ", "second break `´ attempt");`
but the lambda didn't seems to fail.

**Comment by onedotover** [comment]
Thanks @jperata. I just tried it as well and cannot get it to cause an issue. I think I may have been bordering on the maximum response size and misinterpreted it as this issue. Sorry for the false report!

**Comment by jperata** [comment]
No problem, regarding the maximum size of elements, this are the considerations in case you need them or they are causing issues:
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interface-reference#response-format
Will close this issue for now, re-open it if you find anything.
Thanks for the feedback.
