### ISSUE TITLE
Ensure proxy can work for all content types

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#393]
Not just JSON. It should also allow for:
* Images
* Javascript
* HTML
* CSS

Essentially, we want to test and ensure that it is working perfectly for proxying a web server with general content.

In cases where logging is enabled via the proxy, it should **only** still capture JSON though.

**Comment by jkelvie** [comment]
Need to make sure it works with redirects as well

**Comment by jperata** [comment]
Redirect work needs update for http-buffer  to assure response is forwarded directly

**Comment by jperata** [comment]
Currently we have some issues with images, reviewing last standing changes. And moving to current Sprint of work

**Comment by jperata** [comment]
Estimated Remaining Time, 2 days
