### ISSUE TITLE
Weird error with 1.1.0

### ISSUE THREAD

**Issue by OpenDog** [bespoken/bst#395]
We get the below trace when using this url. It happens while processing the payload. The proxy server starts up fine.

https://proxy.bespoken.tools/apps/bravotango/run/google?tableVersion=prod&node-id=e96f9fcc-fd82-4e9e-8a18-c6c2e457dee7

Is there something new around the url requirements?

```
Error: Cannot find module '/Users/bvizy/Source/google/stentor-core/apps/bravotango/run/google'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Function.load (/Users/bvizy/Source/google/stentor-core/node_modules/bespoken-tools/lib/core/node-util.js:6:16)
    at ModuleManager.module (/Users/bvizy/Source/google/stentor-core/node_modules/bespoken-tools/lib/client/module-manager.js:49:43)
    at LambdaServer.invoke (/Users/bvizy/Source/google/stentor-core/node_modules/bespoken-tools/lib/client/lambda-server.js:77:43)
    at IncomingMessage.<anonymous> (/Users/bvizy/Source/google/stentor-core/node_modules/bespoken-tools/lib/client/lambda-server.js:33:22)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)

Process finished with exit code 1
```

**Comment by jkelvie** [comment]
What command are you using to start it?

**Comment by OpenDog** [comment]
bst proxy lambda index.js

**Comment by OpenDog** [comment]
the index.js is built by webpack

**Comment by jkelvie** [comment]
Okay, that is due to the fact that we added a resolver that when proxing lambdas, will use the path to look up the lambda. So, in the case above, it will try to load a lambda named "apps/bravotango/run/google", which I take if obviously does not exist.

Is the path necessary for the call? We thought this was useful behavior because we could not see why anyone would use a path with a lambda.

**Comment by OpenDog** [comment]
Well, when you use the lambda with the application gateway you may want to hide some information in the path.

**Comment by jkelvie** [comment]
Right, but we don't even pass this information along when using the proxy. Is there any reason you want to use it with the proxy?

**Comment by OpenDog** [comment]
We can test without the path, but then we need another way to sneak in dynamically the skill id and the platform. Get them from the query parameters. 

Perhaps if we could customize the fake lambda context BST creates for the call ... ala app GW templating. I'm not sure.

**Comment by jkelvie** [comment]
The query parameters are fine. But can you leave out the path? I don't understand how you are using the path with the proxy, since it doesn't propagate it.

**Comment by OpenDog** [comment]
It did propagate it in the lambda context.

**Comment by OpenDog** [comment]
lambdaContext.request.url

**Comment by OpenDog** [comment]
it was convenient. Same url as the production.

**Comment by jkelvie** [comment]
Okay, that was what I was missing - sorry, did not realize you were using that. I understand now....thinking about it.

**Comment by jkelvie** [comment]
I suggest we just change the Lambda resolution behavior to only take effect if the user does NOT specify a lambda file when starting the proxy. @jperata what do you think? 

This will allow lambdas to be resolved dynamically if one is not specified, but if one is, then the path is not used (and passed along as it has been in the past, allowing this sort of call to continue to work)

**Comment by jperata** [comment]
Agree, new behavior will be:
if (bst proxy called with file) {
  invoke file;
} else {
  if ( path in url ) {
    invoke path
  } else {
    Warning to set up a file or path
}
}

**Comment by OpenDog** [comment]
Approved. 😄

**Comment by jperata** [comment]
@OpenDog Updating to version 1.1.1 should solve the issue.
