### ISSUE TITLE
Use docker-style unique names instead of UUID

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#40]
Could this work?
http://frightanic.com/computers/docker-default-container-names/

**Comment by OpenDog** [comment]
Hehe.

**Comment by jkelvie** [comment]
Maybe put it in the domain name, ala hyperdev.

Example: weird-panda.bespoken.tools

Not sure how to do that though.

**Comment by OpenDog** [comment]
We can use DNS wildcard domain for the registration but we may have to look into the http headers to see what the target domain is.

**Comment by jperata** [comment]
Done as part of the conection to source-name-generator and spoke services
