### ISSUE TITLE
Gateway Timeout while calling encode

### ISSUE THREAD

**Issue by ranjitiyer** [bespoken/bst#402]
Hello,

I'm using the bst-encode API to encode Mp3 files. My code builds up a list of mp3's to encode and fires off requests for all of them at the same time. This is causing all (except one) requests to fail with a GATEWAY_TIMEOUT error, which leads me to think that I might be calling at an excessive rate.

1. Do you guys throttle clients that call the encode API at an excessive rate?
2. What is an acceptable rate at which I can call this API? I have quite a few mp3 files and going one at a time will be extremely slow, given that one mp3 takes roughly 1 min to encode.

Thanks for your help :)
Ranjit

<pre>
https://s3.amazonaws.com/librivox-audio-books/title/0/encoded.mp3
Encoded Url  https://s3.amazonaws.com/librivox-audio-books/title/0/encoded.mp3
https://s3.amazonaws.com/librivox-audio-books/title/0/encoded.mp3
Encoder called
title
0
http://ia800508.us.archive.org/29/items/apocrypha_1605_librivox/apocrypha_25_apuleius_book1_64kb.mp3
title/0/encoded.mp3
https://s3.amazonaws.com/librivox-audio-books/title/0/encoded.mp3
Error  Error: GATEWAY_TIMEOUT
    at ClientRequest.<anonymous> (/Users/ranjiti/work/audiobooks/bespoken/node_modules/bespoken-tools/lib/client/bst-encode.js:83:26)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
</pre>

**Comment by jkelvie** [comment]
Hi Ranjit,

We are not doing any throttling on it intentionally.

We will look into this issue - it is meant to work for this sort of
scenario, so not sure what is causing the issue.

Best,
John

**Comment by ranjitiyer** [comment]
Thanks John. Here's the code, just in case you wanted to a reproducer case to test on your end.

<pre>
const bst = require('bespoken-tools')
const sleep = require('sleep-promise')
const BUCKET = "librivox-audio-books"

// Encode and return S3 url for encoded file
function encode(title, sectionNumber, sourceMp3Url, destS3Bucket) {
	console.log("Encoder called")
	console.log(title)
	console.log(sectionNumber)
	console.log(sourceMp3Url)

	const destS3Key = [title, sectionNumber, 'encoded.mp3'].join('/')
	const destS3Url = ["https://s3.amazonaws.com", destS3Bucket, destS3Key].join('/')

	console.log(destS3Key)
	console.log(destS3Url)

	return new Promise((resolve, reject) => {
		const encoder = new bst.BSTEncode({bucket:destS3Bucket})
		encoder.encodeURLAndPublishAs(sourceMp3Url, destS3Key, (error, encodedURL) => {
		    if (error != null) {
		        console.log('Error ', error)
		        reject(error)
		    } else {
		        console.log('Encoded Url ', destS3Url)
		        resolve(destS3Url)
		    }
		})
	});
}


//const allPromises = []
let index = 0
const urls = ["http://ia800508.us.archive.org/29/items/apocrypha_1605_librivox/apocrypha_25_apuleius_book1_64kb.mp3",
              "http://ia800508.us.archive.org/29/items/apocrypha_1605_librivox/apocrypha_26_apuleius_book2_64kb.mp3",
              "http://ia800508.us.archive.org/29/items/apocrypha_1605_librivox/apocrypha_27_apuleius_book3_64kb.mp3",
              "http://ia800508.us.archive.org/29/items/apocrypha_1605_librivox/apocrypha_28_lifeofplato_hesychius_64kb.mp3",
              "http://ia800508.us.archive.org/29/items/apocrypha_1605_librivox/apocrypha_29_lifeofplato_olympiodorus_64kb.mp3"]


urls.forEach((url) => {
	let random = getRandomIntInclusive(1, 10) * 10000
	sleep(random).then(() => {
	    encode("title", "0", url , BUCKET)
	    	.then((encodedUrl) => {
	    		console.log(encodedUrl)
	    	})
	    	.catch((error) => {
	    		console.log(error)	
	    	})
		});		
})              

</pre>

**Comment by jkelvie** [comment]
Hi @ranjitiyer - I took a look at this issue, using your code (thank you for including that). I first ran through a test file five times that I use, and it worked without issue (without the the randomizer either). Then I ran it through with your files, and experienced the same timeout.

Looking at the files, they are much longer than we typically work with - between 7 minutes and 60 minutes. Though it is not our intention that they fail, I wonder - how do you plan to use them?

The encoder is built for producing audio usable in SSML, which can be up to 90 seconds long. If you are planning to use this audio with the audio player, it is far more forgiving on formats. [From this page](https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#play):
<img width="803" alt="screen shot 2017-11-13 at 10 48 36 pm" src="https://user-images.githubusercontent.com/17267/32762009-d1909b04-c8c4-11e7-986c-8371fe9abe56.png">

So, my thought is you are probably looking to use the Audio Player, in which case modifying (and degrading) the audio is not recommended. Does that make sense? Let me know.

**Comment by ranjitiyer** [comment]
Thanks so much for investigating into this. You are correct; I'm planning to use this for the audio player. Its very encouraging to know that the audio player is more flexible in the formats it accepts. I'll give it a shot and let you know how it goes. 

Once again, your prompt support is very much appreciated 👍 

Ranjit

**Comment by ranjitiyer** [comment]
Hi @jkelvie. Per your suggestion I tested the Audio Player with an non-encoded mp3 file and it worked! I was clearly barking up the wrong tree here. Thanks once again :)
