### ISSUE TITLE
Save state across calls to utter and intend

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#405]
The session state should automatically be preserved between calls.

With these exceptions:
1) It should be reset on a launch command
2) It should be reset when shouldEndSession on the response is set to true
3) It should be reset when --newSession option is set

The sessionID will be saved in a file under .bst named session. The file will contain the sessionID.

The file will be deleted when the session is reset.

**Comment by jperata** [comment]
This closes #243

**Comment by jkelvie** [comment]
Handling the session attributes is an important part - per the issue you referenced.

Should we store them in the file?

**Comment by jperata** [comment]
yes, storing them will be part of the approach
