### ISSUE TITLE
Color code request, response, and error when logging in bst proxy lambda

### ISSUE THREAD

**Issue by rmtuckerphx** [bespoken/bst#408]
Use something like npm chalk to color code the request (blue) and response (cyan) JSON as well as any errors (red). This would be for the logging that shows in the terminal window.

**Comment by jkelvie** [comment]
Yes, great suggestion.

-John

**Comment by jkelvie** [comment]
We should also add color-coding for the URLs that are printed out on startup of the proxy

**Comment by rmtuckerphx** [comment]
Just tested this out. Love it!

**Comment by jkelvie** [comment]
Thanks @rmtuckerphx! Though we may have to adjust the purple color - I have a bit of a hard time picking it up against a black background - take a look:
<img width="895" alt="screen shot 2017-11-27 at 5 19 24 pm" src="https://user-images.githubusercontent.com/17267/33292519-880299f0-d397-11e7-9779-7dfa22a13fd2.png">

I was thinking a blue could work nicely instead. Other suggestions are appreciated.

**Comment by rmtuckerphx** [comment]
My colors are a little different. They should be blue and cyan:

![image](https://user-images.githubusercontent.com/247472/33377602-4fa10bf8-d4cf-11e7-8550-e2e130625a71.png)

![image](https://user-images.githubusercontent.com/247472/33377617-5f626cc6-d4cf-11e7-931e-3f3175c20cf3.png)
