### ISSUE TITLE
Better connection resilience

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#411]
In cases where the server socket hangs up, try to reconnect:
https://github.com/bespoken/bst/blob/7701d87e3dc07554f4c7d2c1123667a31ec7d90f/lib/client/bespoke-client.ts#L52

Also, for connections, add two retries and then give-up:
https://github.com/bespoken/bst/blob/7701d87e3dc07554f4c7d2c1123667a31ec7d90f/lib/client/bespoke-client.ts#L136

**Comment by jperata** [comment]
Adressed on #415
