### ISSUE TITLE
bst utter for languageStrings 'de-DE'

### ISSUE THREAD

**Issue by vidanov** [bespoken/bst#417]
Hi there!

Bespoken is the great tool.
I am using it every day. Could you please help me to set the local for 'bst utter'
 bst utter was ist neues -m model/de-DE.json
I use this like this I get the language strings from   'en-US': {  'translation': { .. in my Lambda. How can I tell to bst utter to use 'de-DE'?

**Comment by jkelvie** [comment]
Hi @vidanov - this is an issue we are currently looking at. We will let you know once it is available.

**Comment by vidanov** [comment]
As a workaround I renamed my de-DE language strings to en-US on the local machine for development, but it is not very good for future. Thank you!

**Comment by jkelvie** [comment]
@jperata related to this issue: https://github.com/bespoken/virtual-alexa/issues/14

**Comment by vidanov** [comment]
@jkelvie `bst proxy` is not ok too. It works with the ASK console only if I put my language strings twice, once for english and once for german. It selects them randomly and not the same as with local `bst utter`

**Comment by vidanov** [comment]
hmm, now I am not sure anymore. It seems the Alexa cloud has problems with accessing your proxy.

**Comment by jkelvie** [comment]
Hi @vidanov - we had another user report a similar issue. I have two thoughts on it:

- Try creating a new endpoint for testing
To do this, delete the directory ~/.bst (`rm -rf ~/.bst`)

- Recreate the skill
Alternatively, try creating a new skill with the same data

And we will try to recreate this ourselves, so far, we are at a loss to explain why this happens, and why it happens in such an intermittent fashion.

**Comment by vidanov** [comment]
@jkelvie I tried to delete the .bst folder. The same problem. 
Then I recreated Lambda function and I have the same issue.

If I send the request from the ASK console, I see the request in my local console and I see as my function gives the answer, but ASK does not get it with the response:
 "The remote endpoint could not be called, or the response it returned was invalid." 


Payload from my side:
{
  "version": "1.0",
  "response": {
    "shouldEndSession": false,
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak> Moin moin aus Hamburg!<say-as interpret-as=\"interjection\">Wow!</say-as> Du hast den Skill von Vidanov Digital aktiviert. Wir freuen uns sehr. Viel Spaß damit! Ein Spiel mit mir. Ja oder Ja? </speak>"
    },
    "reprompt": {
      "outputSpeech": {
        "type": "SSML",
        "ssml": "<speak> Sage Ja um zu spielen und Nein um den Skill zu beenden. </speak>"
      }
    }
  },
  "sessionAttributes": {
    "timestamp": "Wed Dec 20 2017 21:39:44 GMT+0100 (CET)",
    "dateFirst": "Wed Dec 20 2017 21:39:44 GMT+0100 (CET)",
    "dateLast": "Wed Dec 20 2017 21:39:44 GMT+0100 (CET)",
    "msSinceLast": 0,
    "hoursSinceLast": 0,
    "minutesSinceLast": 0,
    "gamesPlayed": 0,
    "gamesSysWon": 0,
    "STATE": "_STARTMODE"
  }
}

**Comment by vidanov** [comment]
This is irregular. Sometimes it works several times and then it does not work. Strange.

**Comment by jkelvie** [comment]
I'm going to give it a try this afternoon. You are testing in the new Test
Console, correct?

**Comment by vidanov** [comment]
It does not depend on the test console, I tried with both consoles and tried with the device too. It is the same problem. It seems to be the issue with your proxy server and ASK communication. The same code works well if I put the function on the AWS.

**Comment by jkelvie** [comment]
Did you try it with a different skill, or recreating the skill?

Just curious - for the one other user that reported this, it resolved it. I
know that is not a satisfying solution.

-John

**Comment by vidanov** [comment]
I recreated the skill.

**Comment by vidanov** [comment]
We have morning in Hamburg. After the night the problem is away. I think sometimes the ASK has connectivity issues.

**Comment by jkelvie** [comment]
Yes, that's good to know. We have seen issues like this, as I mentioned - sometimes, Alexa does not seem to like our proxy, but only for some users, on certain skills and at certain times.

Please let me know if this happens again, though, as I have another idea about it.

And also, thank you again for reporting this and keeping us up to date.

**Comment by jperata** [comment]
Hi @vidanov  
the latest version of bst tools now support indicating the locale
 bst utter -l de-DE was ist neues 
will ensure the request is generated with de-DE locale, and also will look by default to models/de-DE.json

**Comment by vidanov** [comment]
Hi @jperata ! Great news! I will try it next week.
