### ISSUE TITLE
support AWS_PROFILE env var in access key logic

### ISSUE THREAD

**Issue by hakanson** [bespoken/bst#418]
Can the code that looks for access keys support profiles?  For example, this code from https://github.com/bespoken/bst/blob/master/lib/client/lambda-config.ts#L86

```
        // Process anv variables take precedence
        if (awsConfig) {
            this.AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID || awsConfig.get("default.aws_access_key_id");
            this.AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY || awsConfig.get("default.aws_secret_access_key");
            this.AWS_REGION = process.env.AWS_REGION || awsConfig.get("default.region") || "us-east-1";
        } else {
            this.AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
            this.AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;
            this.AWS_REGION = process.env.AWS_REGION || "us-east-1";
        }
```

If prefers the environment variables of `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, but I have multiple sets of these in my `~/.aws/config` and use the profile capability.  I would suggest something like this:

```
var profile = process.env.AWS_PROFILE || "default"; // also support --profile CLI flag

this.AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID || awsConfig.get(profile + ".aws_access_key_id");
// ...
```

More info on AWS_PROFILE from http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html

> AWS_PROFILE – name of the CLI profile to use. This can be the name of a profile stored in a credential or config file, or default to use the default profile.

**Comment by jkelvie** [comment]
We are deprecating the deploy feature - we recommend using ASK CLI instead
