### ISSUE TITLE
Look into working with network proxies with bst proxy

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#419]
Per this conversation:
>@jkelvie I am running it from behind corporate proxy. I have set http-proxy and https-proxy in my Windows-7 PC's environment variables. I am trying to run the sample using this command- bst proxy lambda HelloWorld.js --verbose

> Hi @kunalpatilabg - why are you setting the http-proxy and https-proxy variables? And what are you setting them too?

> kunalpatilabg @kunalpatilabg 09:25
> @jkelvie I have set these variables to use my org's proxy server:port, so that node and npm can use them for connections. Without these settings npm install/update fails.

> jkelvie @jkelvie 09:28
> Hmm...it is probably then not letting any traffic out that does not go through the proxy
> Does that sound plausible?

> kunalpatilabg @kunalpatilabg 09:30
> @jkelvie Yes, it does. Is there any way to configure bespoken to use my proxy settings?

> jkelvie @jkelvie 09:30
> Well, at least one issue I see is that we are using TCP, not HTTP
> So that is likely why it does not go through your proxy
> We also use a non-standard port (5000), which your organization may also block
> I don't know of a simple answer for you - we will need to look into this

**Comment by Stvad** [comment]
Is there any advice/workaround for this? I'm also experiencing the problem of proxy not working within my company network. It's most likely unorthodox port thing and not proxy setup though.

**Comment by jkelvie** [comment]
Hi @Stvad - we have a dev version of the proxy that uses port 80. Please give it a try and let me know if it works. To use it, do the following:
1) Set the bstHost and bstPort args when calling bst proxy, like so:
`bst proxy lambda --bstHost proxy-dev.bespoken.tools --bstPort 80 index.js`

2) The url you will use to then access your skill is different - it is: 
https://proxy-dev.bespoken.tools/?node-id=<SECRET_KEY>

The secret key is found in the ~/.bst/config file. Take it from there and put it in the URL above.

If the firewall issue is just the port, this should resolve it. Let me know.

**Comment by peternann** [comment]
@jkelvie - I have the same problem as OP behind a corporate firewall.

Thanks for the work-around... It does indeed work for me even over our annoyingly stringent proxy/filtering.

But importantly - ngrok 'just works' out of the box...

In my mind the point of such tools is to work in as many annoyingly stringent environments as possible.

**Could you consider moving the default port from 5000 to 80 so that bst proxy can also 'just work' in more environments?**
(Or support both in some simple way... Simpler that the work-around above)
Seems like a good idea to me!

Cheers.

**Comment by jkelvie** [comment]
Hi @peternann this is very helpful to know. We know other users have had the same issue, so we will definitely take a look at this.

**Comment by jkelvie** [comment]
We now utilize port 80 by default in our latest version - 2.3.7 - relates to this issue: https://github.com/bespoken/bst/issues/562
