### ISSUE TITLE
German umlaut problem

### ISSUE THREAD

**Issue by bokostmu** [bespoken/bst#423]
Hey,
first thanks for the nice work done here! It is so much easier testing with your tool than without.

There seems to be a bug which costed me the last hours: If i try to insert a word or phrase in a slot containing a German umlaut (äöü), the request is not send to my locally running lambda function. Alexa (Service Simultor or Echo, doesnt matter) times out saying that the remote endpoint could not be called. The request can also not be found in the logs.

**Comment by jkelvie** [comment]
Hi @bokostmu - sorry you are having that issue - we will take a look at it ASAP

**Comment by jperata** [comment]
@bokostmu could it be possible for you to upload here your model, or a snippet of the part where you use the umlaut

**Comment by bokostmu** [comment]
@jperata  I uploaded it here: https://github.com/bokostmu/bespoken-umlaute/tree/master
Just copy the model to a new skill and start the linked proxy with `bst proxy lambda index.js`. If you now start the skill you have to say a german city. If you say for example Berlin, it works, but if you say Köln or Düsseldorf instead it does not.

**Comment by jperata** [comment]
Hi @bokostmu 
We have update our servers and now everything should work correctly, you will need to update your proxy tool to the latest  (npm install -g bespoken-tools) , but everything should work ok.
We have the added bonus that if you're using a models/de-DE.json once your proxy is up , you can now do
`bst launch -m de-DE`
in another terminal to launch
or
`bst utter Düsseldorf`
to simulate without going to the web
