### ISSUE TITLE
404 error during installation of latest version of bespoken-tools

### ISSUE THREAD

**Issue by JoshTumath** [bespoken/bst#434]
When I install the latest version of bespoken-tools, i receive the following error:

```
npm ERR! 404 no such package available : @types/uuid
npm ERR! 404
npm ERR! 404  '@types/uuid' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'virtual-alexa'
```

**Comment by jkelvie** [comment]
Hi @JoshTumath - I am thinking this is an issue with npm. I just tried installing it using this command did not have an issue. I used this command this morning: 
`npm install bespoken-tools -g`

And that worked fine for me. Is that the same command you are using? Does it work now?

**Comment by JoshTumath** [comment]
Thanks @jkelvie. Yes, it was an issue with our npm's configured registry. I hadn't investigated enough before reporting, so apologies for the spam.

**Comment by jkelvie** [comment]
Not a problem - glad we could help!
