### ISSUE TITLE
bespoken on raspberry pi

### ISSUE THREAD

**Issue by dtavares07** [bespoken/bst#435]
Hi. 

I'm trying  to use bespoken on a raspberry pi, but I get the following error message when I use the command sudo bst proxy http 5000.

2018-03-19T20:27:38.550Z INFO BST         Node Version: v4.8.2
2018-03-19T20:27:38.756Z ERROR SOCKET      SocketError: ENOTFOUND Message: getaddrinfo ENOTFOUND bst.xappmedia.com bst.xappmedia.com:5000

Am I missing something? 

Best Regards,
Daniel Tavares

**Comment by jperata** [comment]
Hi, it seems you are using a really old version of the proxy, called bespoke-tools (without the "n").
Could you verify?, it's supposed to be bespoken-tools

**Comment by dtavares07** [comment]
Thanks you were right. 
I was using bespoke-tools instead of bespoken-tools

:)
