### ISSUE TITLE
In bst utter -> resolutionsPerAuthority is not supported

### ISSUE THREAD

**Issue by vidanov** [bespoken/bst#436]
slot.resolutions.resolutionsPerAuthority is not supported

![alexa skills kit developer console 2018-04-02 23-59-35](https://user-images.githubusercontent.com/7902797/38218419-0807abde-36d2-11e8-9764-0aa23d132a4a.jpg)

**Comment by jkelvie** [comment]
Per this issue - @ecruzado - please incorporate the latest virtual-alexa into bst. It has support for entity resolution. Details are here:
https://github.com/bespoken/virtual-alexa/blob/master/docs/EntityResolution.md

**Comment by ecruzado** [comment]
https://github.com/bespoken/bst/pull/452
