### ISSUE TITLE
Fix test failure due to hard errors on utterances not matching

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#457]
In new versions of virtual-alexa, if an utterance does not match an intent, we throw an error.

Previously, it would just "fallback" and match a random intent. This change in behavior causes one of our bst tests to fail:
https://circleci.com/gh/bespoken/bst/455?utm_campaign=build-failed&utm_medium=email&utm_source=notification

We need to fix the test to accommodate this new behavior.

**Comment by ecruzado** [comment]
https://github.com/bespoken/bst/pull/468

**Comment by ecruzado** [comment]
This ticket wont need QA
