### ISSUE TITLE
Issues with bst proxy?

### ISSUE THREAD

**Issue by jstreb** [bespoken/bst#458]
This looks like a similar issue to https://github.com/bespoken/bst/issues/437

I am consistently seeing the error message of "There was an error with the requested skill's response". When I look at the device logs I can see that the it is the hitting the correct endpoint. When I go directly to the endpoint I get this message:

SSLPIPE ERROR: No pipe found for: lonely-zander-8wcfev.bespoken.link/

Any help is greatly appreciated.

**Comment by jkelvie** [comment]
Hi Jesse, thank you for reporting this issue. We have also observed it and are working on a fix now.

In the meantime, you can use the proxy still by using a URL like this:
https://proxy.bespoken.tools/?node-id=<SECRET_KEY>

You get the secret key by printing out the contents of the file ~/.bst/config.

Sorry about the inconvenience, and we expect to have this resolved soon.

**Comment by jstreb** [comment]
wow, thank you for the incredibly prompt response. Very much appreciated!

**Comment by jkelvie** [comment]
Hi @jstreb - the issue should be resolved now. You can resume using the link as provided in the console.
