### ISSUE TITLE
Add improved BST stats

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#462]
We want to augment the existing BST stats. We want to capture
* NodeID (optional - since we allow for tests to be run without creating a config)
* Command - utter, intend, speak, launch, proxy, test, e2e)
* Event (optional) - subcategory of command - for proxy it is connect, forward, drop
For all the other commands, it should just be run for now. We may add other events as we go forward.
* Timestamp
 
This will need to be a new endpoint. Probably should be on source-api, where this data can be sent from the client.

The call should be done in a way that:
* It never causes an error (it should fail silently)
* It is async, and does not hold up any other processing

Finally, we should capture the data in Mongo - it is just too hard to query Dynamo :-)

We will need to port over old data as part of this - that will be a separate task.

**Comment by ecruzado** [comment]
This can be tested with beta version of bst

**Comment by MKen-li** [comment]
Marked as verified:
build = bespoken-tools@beta
