### ISSUE TITLE
Modify BST Server to write logs 

### ISSUE THREAD

**Issue by jperata** [bespoken/bst#469]
This is a subtask of #462 and depends on https://github.com/bespoken/source-api/issues/107 being completed.

Using the new endpoint for stats registering from the server we have the nodeID and the connect , forward and drop events registered.

We already use  https://github.com/bespoken/bst/blob/master/lib/server/statistics.ts it would be a matter of adapt it to use the endpoint directly (it's right now writing to dynamo).

Calls to the endpoint should be asynchronous but should not wait for the result to continue with the normal flow. Since this logs are at server level, we can output the errors to console to troubleshoot or validate the functionality.

**Comment by ecruzado** [comment]
https://github.com/bespoken/bst/pull/475
