### ISSUE TITLE
Modify BST Client to register stats

### ISSUE THREAD

**Issue by jperata** [bespoken/bst#470]
This is a subtask of #462 and depends on bespoken/source-api#107 being completed.

On each call to a bst command we should register a stat using the source-api stats endpoint that is going to be created.
It should call to the endpoint asynchronously without waiting for the response. We shouldn't log the results directly to the console, we could register the errors on the .bst folder under an error file.  We shouldn't write the error in the bst-debug.log file since we shouldn't polute the user folder with stats errors. But we can use a similar approach.

**Comment by ecruzado** [comment]
https://github.com/bespoken/bst/pull/476
