### ISSUE TITLE
bst speak - in German?

### ISSUE THREAD

**Issue by vidanov** [bespoken/bst#483]
Is it possible to use bst speak in other languages?

**Comment by jkelvie** [comment]
Hi @vidanov it is possible - there is a flag "--locale" that you can specify for this. The "--voiceID" can be specified as well - it can be any of the Amazon Polly voices listed here:

I noticed that our help command does not list these options - I added an issue to track fixing this:
https://github.com/bespoken/bst/issues/484

Please also keep in mind our end-to-end testing scripts. These work in every language Alexa supports, and allow for writing end-to-end tests that interact with Alexa. Read more here:
https://bespoken.io/end-to-end/getting-started

**Comment by vidanov** [comment]
Thank you a lot!
