### ISSUE TITLE
bug(LambdaServer): SpeechletResponse was null after AudioPlayer.PlaybackNearlyFinished

### ISSUE THREAD

**Issue by CoreyCole** [bespoken/bst#485]
### Description:
I've developing a skill that uses the audio player. When testing using a real lambda server on aws, I don't see any system exceptions. When testing locally with `bst.LambdaServer` I get `System.ExceptionEncountered` following an `AudioPlayer.PlaybackNearlyFinished` with the error:
```json
  "request": {
    "type": "System.ExceptionEncountered",
    "cause": {
      "requestId": "amzn1.echo-api.request.fe74d1d8-2422-42d1-a9e0-2d9da34ae60a"
    },
    "error": {
      "type": "INVALID_RESPONSE",
      "message": "SpeechletResponse was null"
    },
    "locale": "en-US",
    "requestId": "amzn1.echo-api.request.777cf36e-9d05-4d77-8530-f4e88148bf22",
    "timestamp": "2018-08-27T23:43:10Z"
  }
```
This is a new occurance that wasn't happening in recent weeks. We have a check inside `playbackNearlyFinished` where we detect if it has been called more than once before `playbackFinished` was called (similar to pattern seen in [amazon example here](https://github.com/alexa/skill-sample-nodejs-audio-player/blob/sdkv1/multiple-streams/lambda/src/audioEventHandlers.js#L48)). We used to never hit this check, but now we are. When it does happen, and we call `context.succeed()`, we get the error detailed above.

### Environment:
- Version: "bespoken-tools": "2.0.9"
- OS: MacOS 10.13.6
- Node version: v8.11.1

### Steps To Reproduce
1. Use a skill that utilizes ENQUEUE behavior in PlaybackNearlyFinished
1. In some sort of persistent object, keep track of when `PlaybackNearlyFinished` is called to make sure files are not enqueued twice (see example [here](https://github.com/alexa/skill-sample-nodejs-audio-player/blob/sdkv1/multiple-streams/lambda/src/audioEventHandlers.js#L48))
1. See that `PlaybackNearlyFinished` is called more than once in a single audio loop (before `PlaybackFinished` was called)
1. When calling `context.succeed()` as suggested by amazon, see that a SpeechletResponse System Exception is raised

### Expected behavior
1. PlaybackNearlyFinished should only be called once per audio loop
1. If it is called more than once, I should not get a SpeechletResponse error when returning `context.succeed()`

### Actual behavior
1. PlaybackNearlyFinished is called more than once per audio loop sometimes
1. When calling `context.succeed()`, I get SpeechletResponse System Exception Encountered

### Code example
https://github.com/alexa/skill-sample-nodejs-audio-player/blob/sdkv1/multiple-streams/lambda/src/audioEventHandlers.js#L48

### Additional context
I've asked amazon about this problem before I isolated it to only occur on my local machine here: https://forums.developer.amazon.com/questions/182514/speechletresponse-was-null-after-audioplayerplayba.html

**Comment by ig-perez** [comment]
Hello Corey, thanks a lot for letting us know and sorry for the inconveniences it might have caused. I'm going to coordinate with the Technical Team, and we’ll get back to you as soon as possible.

Have a great day!

​Iván Pérez
**Customer Success**
Bespoken
w: | bespoken.io  e: ivan@bespoken.io

**Comment by jperata** [comment]
Hi, we reviewed the case, 
Expected behavior
    **PlaybackNearlyFinished should only be called once per audio loop**
    The code sample that you sent itself indicates that the case is that this event can be executed more than one time, hence using the enqueue permanent attribute to handle the issue.

    **If it is called more than once, I should not get a SpeechletResponse error when returning context.succeed()**
The latest version of the code sample using alexa sdk v2 , use a different "empty" response for cases like the nearlyFinished, using
              ```
  return this.context.succeed({
                    "version": "1.0",
                    "response": {},
                });

```
   seems to be closer to what Amazon is using for this cases.
