### ISSUE TITLE
Incorporate version number into stats

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#503]
**Is your feature request related to a problem? Please describe.**
We would like to know what version number of bst people are using.

**Describe the solution you'd like**
We should include the version number in the stats reports. It should be an additional part of the payload, as well as capture as its own column in the DB.

**Comment by jperata** [comment]
Change released on Version 2.0.30
To test, ensure the environment variable for source-api is pointing to dev. Verify the generated stats records for each command, they should include the version as a field.

This also includes a different stat record for the proxy command usage apart from the event ones.

**Comment by MKen-li** [comment]
Marked as verified
Build bst 2.0.30
