### ISSUE TITLE
Configuration overrides via environment variables are not documented

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#505]
### Description:
We do not document how users can override configuration values using environment variables.

### Environment:
All versions

### Steps To Reproduce
Look at the docs, see there is no reference to overriding configuration via environment variables.

### Expected behavior
Under the configuration section for both unit-testing and end-to-end testing, there should be a section at the end that explains environment variables can be overridden. It should be titled: "Overriding Values". The section should:

- Explain how the overrides work
- Provide an example of an override

**Comment by MKen-li** [comment]
Marked as verified
