### ISSUE TITLE
Include virtual device display and debug payload in responses for test command

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#507]
**Is your feature request related to a problem? Please describe.**
Our customers would like to be able to write tests against all parts of the JSON payload returned by virtual devices.

This is so they can test display output, as well as other elements, within their YAML-based tests.

**Describe the solution you'd like**
* By default, set debug to true when calling the virtual device
* Include the "display" template info in a new top-level element, "display", if the display template exists
* Move the debug.rawJSON element to the top-level of the payload as "raw" (note that move means that it should be removed from the debug property - we do not want it appear twice).

Moving the elements around is just meant to make the payload easier to understand and write tests against.

The display property should be set if a directive is found with the name "RenderTemplate". It should take the contents of the directive.payload element of the RenderTemplate and set it as the top-level "display" property on the transformed payload.

The response payload, after manipulation, will then look like this:
```
{
    "transcript": "This is the transcript",
    "debug": {
        "transcriptTimeMS": 1000,
    },
    "display": {
       //Display info  - should not be set if there is not display template 
   }
}
```

This describes how to handle this for Alexa - the same should also be done for Google (I'm not sure where this data is stored for Google either, at this point).

**Describe alternatives you've considered**
I considered just doing a straight passthrough on the debug data, but that is more difficult to write tests against. Having a top-level display element is easier to work with.

**Additional context**
More info on the display payloads for Alexa can be found here:
https://developer.amazon.com/docs/alexa-voice-service/templateruntime.html#bodytemplate1

**Comment by dmarvp** [comment]
@jkelvie what should happen with the card property? Currently we take parts of the display payload to create that one, should that stay the same?

**Comment by jkelvie** [comment]
Yes, I think so.

**Comment by ecruzado** [comment]
https://github.com/bespoken/virtual-device/pull/153

**Comment by ecruzado** [comment]
This can be tested using the last beta of bst.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-aws-48
