### ISSUE TITLE
E2E tests shows undefined whenever there is an internal error

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#514]
### Description:
When running e2e scripts, if there is an internal error, the output shows an error saying that we received "undefined" instead of the expected value.

### Environment:
- Version: BST 2.0.29

### Steps To Reproduce
1. Run two e2e scripts with the same token at the same time.

### Expected behavior
If there is an error, a message explaining the error should be shown.

### Actual behavior
The utterance that fails says that it fails because of "undefined"

### Additional context
Virtual device exposes the error messages trough a json with the following structure:
```json
{ "error": "Error message"}
```
The idea is to capture those and show a friendlier message trough the bst output.

**Comment by ecruzado** [comment]
https://github.com/bespoken/skill-testing-ml/pull/124

**Comment by ecruzado** [comment]
This can be tested using the last beta of bst. 

`npm i bespoken-tools@2.0.32
`

**Comment by MKen-li** [comment]
Marked as verified
Build bespoken-tools@2.0.32
Only one issue pending that is not a blocker and will be fix in the next sprint
