### ISSUE TITLE
Option to skip/ignore internal errors

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#516]
**Is your feature request related to a problem? Please describe.**
Sometimes e2e tests can fail because of things out of our control. For example, an AVS outage. When that happens, we are marking the test as failed. While this behavior is correct, we want to make an option available to skip/ignore errors that are not because of failed assertions.

**Describe the solution you'd like**
Include an optional property under testing.json `"ignoreExternalErrors"=true/false`.
If false (default) everything should work as it does now. If true, tests that fail because of external reasons should be marked as ignored/skipped.

**Comment by ecruzado** [comment]
need to release a new version

**Comment by ecruzado** [comment]
This can be tested using the last beta of bst. 

`npm i bespoken-tools@2.0.32
`

**Comment by MKen-li** [comment]
Marked as verified
Build bespoken-tools@2.0.32
Only one issue pending that is not a blocker and will be fix in the next sprint
