### ISSUE TITLE
The Include, exclude properties don't have the correct json structure 

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#519]
**Preconditions**
None.

**Steps To Reproduce**
1. Use the attribute "tags" on a yaml
2. add more than one value for include or exclude

**Expected behavior**
The syntax should be "include": ["sanity","smoke", "regression"]

**Actual behavior**
The syntax is : "include": "sanity,smoke,regression"

**Screenshots**
None.

**Environment:**
 - OS: Win 10
 - Browser None
 - Version bespoken-tools@2.0.32

**Additional context**
None.

**Comment by jkelvie** [comment]
Why do we want to force people to write an array? I prefer the "include": "sanity,smoke,regression" syntax.

**Comment by jperata** [comment]
We are doing it to be consistent with the properties that are already present on the testing.json file, if we keep the "sanity,smoke,regression", it will be the only property that have that specific syntax.

**Comment by jperata** [comment]
Overwriting properties should use the initial format though, bst test --include sanity,smoke, regression

**Comment by jperata** [comment]
Ready to test on bst version 2.0.33

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.0.33
