### ISSUE TITLE
different error messages when using the skip flag

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#521]
**Preconditions**
None.

**Steps To Reproduce**
1. Enable Flag
2. Execute 2 test that uses the same token
3. Repeat step 1 and 2 but with the flag disable

**Expected behavior**
Message handling is the same.

**Actual behavior**
Flag on = Test Name
Flag off = Locale + Test Name + utterance

**Screenshots**
![flag off](https://user-images.githubusercontent.com/39920441/46562278-f5540380-c8c0-11e8-9cb4-3320f2c86888.png)
![flag on](https://user-images.githubusercontent.com/39920441/46562279-f5540380-c8c0-11e8-8771-e92e80057dd9.png)

**Environment:**
 - OS: Win 10
 - Browser None
 - Version bespoken-tools@2.0.32

**Additional context**
This issue is related to.
https://github.com/bespoken/bst/issues/516
https://github.com/bespoken/bst/issues/514

**Comment by dmarvp** [comment]
check back after work on #523

**Comment by MKen-li** [comment]
Closing ticket, verified on #523
