### ISSUE TITLE
Update e2e scripts with enhanced error handling

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#523]
**Description.**
After work on https://github.com/bespoken/virtual-device/issues/155 and https://github.com/bespoken/virtual-device/issues/159 is completed, modify the error handling in bst to work with those updates. 

**Describe the solution you'd like**
If there was an unhandled error on virtual device after one or more utterances that were handled correctly, then the output should reflect that by showing the error at the utterance level.

**Additional context**
Changes should be done in a way that they work with our current way of sending errors trough virtual device. In other words, this should not remove changes done in https://github.com/bespoken/skill-testing-ml/pull/124

**Comment by ecruzado** [comment]
Test with bespoken-tools@2.1.1

**Comment by MKen-li** [comment]
Marked as verified
Build bespoken-tools@2.1.1
