### ISSUE TITLE
sequential test aren't supported

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#525]
**Preconditions**
"batchEnabled": false,.

**Steps To Reproduce**
1. Run the test

**Expected behavior**
The Run is run correctly.

**Actual behavior**
The system shows the error (see attach screenshot).

**Screenshots**
![sequencial test](https://user-images.githubusercontent.com/39920441/47188506-f2640480-d2fd-11e8-83cf-d4a5ce7e837d.png)

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version bst 2.0.35

**Additional context**
This issue affects the yaml editor on the dashboard.

**Comment by dmarvp** [comment]
I would advise stopping work on this issue for now. We need to first research if we can implement something like pusher from within the virtual device itself.
