### ISSUE TITLE
Testing google actions have some issues due jest supported formats

### ISSUE THREAD

**Issue by jperata** [bespoken/bst#526]
### Description:
When running tests for google actions, unless the jest properties are modified importing errors are showed.

### Environment:
- Version: 2.0.32
- OS: All
- Node version: 8

### Steps To Reproduce
1. Download this project
[dialogflow-facts-about-google-nodejs.zip](https://github.com/bespoken/bst/files/2506861/dialogflow-facts-about-google-nodejs.zip)

2. Run npm install inside the functions folder
3. Remove the jest section from the testing.json file
4. Run bst test from the functions folder

### Expected behavior
Test run and shows results related to that intent

### Actual behavior
shows error 

### Code example
[dialogflow-facts-about-google-nodejs.zip](https://github.com/bespoken/bst/files/2506861/dialogflow-facts-about-google-nodejs.zip)

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.1.0-2
