### ISSUE TITLE
Interactions with format Intent Slot=SlotValue are not working

### ISSUE THREAD

**Issue by jperata** [bespoken/bst#527]
### Description:
Interactions with format Intent Slot=SlotValue are not working, they should be read as an intent and their slots, but instead 

### Environment:
- Version: 2.0.32
- OS: All
- Node version: 8

### Steps To Reproduce
1. Download this project
[dialogflow-facts-about-google-nodejs.zip](https://github.com/bespoken/bst/files/2506861/dialogflow-facts-about-google-nodejs.zip)

2. Run npm install inside the functions folder
3. Run bst test from the functions folder

### Expected behavior
Test run and shows results related to that intent

### Actual behavior
It shows "No intentName matches utterance: tell_fact category=history. "

### Code example
[dialogflow-facts-about-google-nodejs.zip](https://github.com/bespoken/bst/files/2506861/dialogflow-facts-about-google-nodejs.zi

### Additional context
The testing.json on this file is modified to avoid  #526

**Comment by MKen-li** [comment]
Moving back to dev, the prompt is being taken as another utterance. also, the title - "Using intent slot": is being taken as utterance as well 
 √ prompt == "Sure, here's a history fact"
√ Using intent slot

**Comment by askirk** [comment]
Anyone have a link to the (possibly updated) documentation for a proper way to test an intent with a specific slot?

**Comment by jperata** [comment]
@askirk https://read.bespoken.io/unit-testing/guide/ have the latest documentation and includes the intents and slots format.

**Comment by jperata** [comment]
The issue presented for the √ prompt == "Sure, here's a history fact" is due to the file using tabs instead spaces.
Yaml forbids tabs http://yaml.org/faq.html , it seems our library for parsing is ignoring the tabs, putting the prompt at the same level, replacing the tab with spaces shows the code working correctly.

**Comment by MKen-li** [comment]
Marked as verified
version bespoken-tools@2.0.32
