### ISSUE TITLE
bst test -help section no accurate 

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#528]
**Preconditions**
None.

**Steps To Reproduce**
1. run the command "bst test -h"

**Expected behavior**
1. The description should mention that it works for e2e test as well @jperata define the expected message
2. Description for version and help should start with a capital letter.

**Actual behavior**
1. The description of the help command only mentions the unit test
2. version and help descriptions are lower cases

**Screenshots**
![bst test help](https://user-images.githubusercontent.com/39920441/47375271-8561bd80-d6b5-11e8-9985-a9b60daf57fe.png)

**Environment:**
 - OS: Win 10
 - Version bespoken-tools@2.0.35

**Additional context**
None.

**Comment by jperata** [comment]
Modified the description to include e2e on https://github.com/bespoken/bst/pull/536.

Both the version and help are autogenerated by commander (the tool we use to work on command line).

We can not edit that autogenerated test unless we fork the commander library and then edit those tests. It can be done, but then we would need to mantain that fork to ensure it's always updated. I don't think is worthy.

**Comment by MKen-li** [comment]
Marked as verified
Build bespoken-tools@2.1.1
