### ISSUE TITLE
Remove snapshots from the test results

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#530]
**Preconditions**
None.

**Steps To Reproduce**
1. Run a working yml test

**Expected behavior**
The test results don't show the Snapshots field

**Actual behavior**
The test result shows the snapshot field that is never use

**Screenshots**
None

**Environment:**
- OS: Win 10
 - Version bespoken-tools@2.0.35

**Additional context**
None.

**Comment by dmarvp** [comment]
@MKen-li closing this one given @jkelvie findings.
