### ISSUE TITLE
Tabs in a yml file doesn't get validated correctly

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#533]
**Preconditions**
None.

**Steps To Reproduce**
1. Create a yml test using tabs.

**Expected behavior**
1. The system shows the error "A YAML file cannot contain tabs as indentation"

**Actual behavior**
We omit the tabs and in doing so we make some responses be taken as utterances

**Screenshots**
None

**Environment:**
 - OS: Win 10
 - Version bespoken-tools@2.1.1

**Additional context**
None.

**Comment by dmarvp** [comment]
I think this is an issue for skill-testing-ml, but bst library should be updated once that is done, as well as the Dashboard.

**Comment by jperata** [comment]
Can be tested on version 2.1.2 of bst

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.1.2
