### ISSUE TITLE
When all of the test are marked as skipped bst shows as fail

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#537]
**Preconditions**
None.

**Steps To Reproduce**
1. Mark all test as skip or set tags so no test is run

**Expected behavior**
The test suite is marked as skipped

**Actual behavior**
The test suite is marked as fail

**Screenshots**
![skip fail](https://user-images.githubusercontent.com/39920441/48430916-68615d00-e73e-11e8-9524-27be83173b46.png)

**Environment:**
 - OS: Win 10
 - Version bespoken-tools@2.1.1

**Additional context**
None.

**Comment by MKen-li** [comment]
The issue is fixed in bst but when we use the jest html report the skip test is displayed as "Global"
![global](https://user-images.githubusercontent.com/39920441/49258430-6fa58d80-f403-11e8-8d24-f6efe40b065e.png)
Moving back to dev

**Comment by jperata** [comment]
Can be tested on 2.1.8

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.1.8
