### ISSUE TITLE
bst test does not write logs to bst-debug.log

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#540]
### Description:
When an internal exception happens running bst test, no output is written to our log file.

### Environment:
- Version: 2.0.32
- OS: macOS Mojave
- Node version: v9.3.0

### Steps To Reproduce
1. Disconnect from the internet.
2. Run `bst test` for an e2e script.

### Expected behavior
We get a clear error message and the internal exception is written to a log file.

### Actual behavior
We get a misleading error message and the internal exception is not written anywhere.

### Additional context
- There is a log file called "bst-debug.log" used for commands like proxy and others, we could use that same file to have any internal exception written there. 
- The logs should include the timestamp
- These logs will be used when a user reports errors with bst test.

**Comment by jperata** [comment]
Ready for review on bst latest beta (v. 2.3.5) 
- Apart from the scenario indicated in the issue description, another scenario can be tested by putting an incorrect filename in the handler in the testing.json.
The console output would have a small message reflecting the issue, but the bst-debug.log would have the full stack for the error.

**Comment by MKen-li** [comment]
Moving back to dev

**Comment by jperata** [comment]
Fixed issue with logging errors in latest beta  (v. 2.3.6)

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.3.6
