### ISSUE TITLE
Permission error with global install

### ISSUE THREAD

**Issue by dnetoMOB** [bespoken/bst#546]
### Description:
When trying to perform a global installation of the CLI, the installation fails due to a permission error possibly related to a dependency with `aesprim-browser.js`

### Environment:
- Version: 2.1.2 (latest)
- OS: Mac 10.14.1
- Node version: 8.10.0

### Steps To Reproduce
1. Uninstall bespoken-tools, or use a system without it already installed.
2. Attempt an install with `sudo npm install -g bespoken-tools`

### Expected behavior
BST CLI should be installed.

### Actual behavior
A permissions error is generated and the package is not installed.

### Terminal output on install attempt
```
➜ sudo npm install -g bespoken-tools

npm WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.
/usr/local/bin/bst-server -> /usr/local/lib/node_modules/bespoken-tools/bin/bst-server.js
/usr/local/bin/bst-test -> /usr/local/lib/node_modules/bespoken-tools/bin/bst-test.js
/usr/local/bin/bst -> /usr/local/lib/node_modules/bespoken-tools/bin/bst.js

> fsevents@1.2.4 install /usr/local/lib/node_modules/bespoken-tools/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/bespoken-tools/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> jsonpath@1.0.0 postinstall /usr/local/lib/node_modules/bespoken-tools/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

sh: generated/aesprim-browser.js: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsonpath@1.0.0 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsonpath@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dneto/.npm/_logs/2018-12-05T21_20_47_263Z-debug.log
```
### Additional context
I ran the install again by allowing unsafe permissions with this command:
`sudo npm i -g bespoken-tools --unsafe-perm=true`
After that the tool installed correctly and is operating as expected.

**Comment by jricaldi** [comment]
@dnetoMOB please don't use `sudo` with `npm`. This is a good article which explain well the point https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92

**Comment by jperata** [comment]
There seems to be an issue with one of our dependencies, https://github.com/dchester/jsonpath/issues/105, the --allow-root flag seems to do the same job as using sudo according to that issue. At the moment we haven't found a better alternative to replace jsonpath.

**Comment by error404notfound** [comment]
I have the same problem, but even when I use the following. 
\sudo npm i -g bespoken-tools --unsafe-perm=true

 I still get the same errors. 

sh: generated/aesprim-browser.js: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsonpath@1.0.0 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsonpath@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


Really keen to get started, any hints as to how I can get it installed?

**Comment by error404notfound** [comment]
Thank you for your help and time. 
I am all installed now are getting underway.

**Comment by jperata** [comment]
The changes can be tested in the alpha release (2.1.9)

**Comment by MKen-li** [comment]
Marked as verified
Build =  bespoken-tools@2.1.9
