### ISSUE TITLE
Running a simple test with google function is not finishing

### ISSUE THREAD

**Issue by jperata** [bespoken/bst#547]
### Description:
Running a simple test with google function doesn't return the result as pass or fail

### Environment:
- Version: 2.1.2
- OS: Mac
- Node version: 8

### Steps To Reproduce
1. Download project [minGoogleProject.zip](https://github.com/bespoken/bst/files/2655212/minGoogleProject.zip)

2. Run npm install on it
3. Run bst test

### Expected behavior
Test pass

### Actual behavior
The request and response logs out and then the test halts

### Additional context
The error should be on virtual google assistant library, but bst needs to update once it's solved in there.

**Comment by jperata** [comment]
This can be tested on latest alpha (2.1.9)

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.1.9
