### ISSUE TITLE
bst speak error handling

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#549]
### Description:
Whenever there's an error with bst speak, we only receive the following message: `Sorry, something went wrong. Please try again in a few minutes.` and no meaningful information.

### Environment:
- Version: bst 2.1.8

### Steps To Reproduce
1. Force an error in bst speak.

### Expected behavior
An error with meaningful information coming back from virtual device should be shown.

### Actual behavior
We only show `Sorry, something went wrong. Please try again in a few minutes.`

### Additional context
Virtual device response payload has an "error" string property containing a friendly error message that should be used here.

**Comment by ecruzado** [comment]
https://github.com/bespoken/bst/pull/551

**Comment by ecruzado** [comment]
can be tested on bespoken-tools@2.1.10

**Comment by dmarvp** [comment]
Verified with bespoken-tools@2.1.10
