### ISSUE TITLE
Migrate BST server from Hyper to ECS

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#550]
### Description
As hyper.sh has decided to close before on Jan 15. We need to migrate our bst server to ECS.
This involves (both for dev and prod):

- Set up target groups in ECS
- Point to the right target group in our EC2 Load Balancer
- Create the task definitions for bst server
- Create scripts for creating the service in ECS 
- Create scripts for updating the service in ECS
- Update the circle 2.0 scripts for deployment
- Update the DNS records to point to the EC2 Load Balancer

### Additional Context
- Since this is an open sourced project, we should not expose our ARNs in the scripts if possible (use env vars).
- Take a look at other projects like virtual-device to get an idea on how to do the above steps.

**Comment by ecruzado** [comment]
https://github.com/bespoken/bst/pull/553

**Comment by dmarvp** [comment]
Successfully migrated.
