### ISSUE TITLE
bst speak doesn't call the virtual device the first time that is used

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#552]
### Description:
When calling bst-speak for the first time, it saves the token but it doesn't do the call to the virtual device.

### Environment:
- Version: 2.1.9
- OS: MacOS
- Node version: 9.3.0

### Steps To Reproduce
1. Call bst speak for the first time like this:
`bst speak -t <token> "what time is it?"

### Expected behavior
The token is saved and the virtual device is called and a response is returned.

### Actual behavior
The token is saved but nothing else happens.

### Additional context
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/6411740/50567326-ad067f00-0d11-11e9-93f8-f4c090a43ae1.png">

**Comment by MKen-li** [comment]
Marked as not reproducible.
Closing ticket
