### ISSUE TITLE
Is Amazon polly (used for speech to text and text to speech conversion) a free tool or I need to pay for this.

### ISSUE THREAD

**Issue by DipaliK9** [bespoken/bst#558]
Is Amazon polly (used for speech to text and text to speech conversion) a free tool or I need to pay for this.
I am looking for free tool please suggest.

**Comment by jperata** [comment]
Hi, Polly has a free tier for the first year, but it depends on the number of characters you convert https://aws.amazon.com/polly/pricing/
If you refer to us using Polly for our e2e testing, your virtual devices have a 30 day trial, but then have a cost.
