### ISSUE TITLE
Error - Forbidden

### ISSUE THREAD

**Issue by manuabalos** [bespoken/bst#567]
### Description:
First, sorry with my bad english. My output when I pass my tests are show an error.

### Environment:
- Version: 2.1.22 and 2.3.4 (bespoken)
- OS: MacOS
- Node version: v11.7.0

### Steps To Reproduce
1.  bst test

### Actual behavior
When my tests finish to run (passed successfully) Im receiving in my output this message: 

Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        2.644s, estimated 4s

Error - Forbidden:
null

It's is a problem because circleci detect it like an error.

### Code example
![captura de pantalla 2019-03-05 a las 10 58 43](https://user-images.githubusercontent.com/11856433/53797306-36b31280-3f36-11e9-958a-5803318c72fc.png)

**Comment by jkelvie** [comment]
Hi @manuabalos - I'm not sure what would cause that without knowing more about your tests. You can share them privately with me jpk@bespoken.io - we can probably provide better feedback based on that.

**Comment by jkelvie** [comment]
I've closed this issue for the time being - @manuabalos please feel free to re-open - we do need more information to act upon it.
