### ISSUE TITLE
Add documentation for skill-testing API

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#571]
**Is your feature request related to a problem? Please describe.**
We do not have documentation for our skill-testing APIs. 

Specifically, we do not document the objects returned by the filter methods, such as:
* test
* interaction
* request
* response
* testSuite

**Describe the solution you'd like**
We should add API reference docs, similar to what we have for virtual-alexa:
https://bespoken.github.io/virtual-alexa/api/

The docs should be auto-generated from the source code using JSDoc, similar to what we do for Virtual Alexa.

The docs should be hosted on a Github Pages site, in the same way that virtual-alexa is. The github pages can be configured similar to virtual-alexa:
* It points at the docs/api folder for its content
* It has a URL https://bespoken.github.io/skill-testing-ml/api

**Describe alternatives you've considered**
Alternatively, we could host the docs as part of the BST API.
This would consolidate our object model between BST and SkillTesting.
This is clearer I think to users, but more difficult to maintain, since the BST classes are created using TypeDoc and skill-testing ones are created with JSDoc.

**Comment by jperata** [comment]
Docs are deployed as requested at:
https://bespoken.github.io/skill-testing-ml/api/index.html

**Comment by jperata** [comment]
Fixed typo's and syntax issues

**Comment by jkelvie** [comment]
Looks good. Nicely done!

**Comment by MKen-li** [comment]
Marked as verified
