### ISSUE TITLE
env: node\r: No such file or directory  running bst test (macOS)

### ISSUE THREAD

**Issue by tripper54** [bespoken/bst#574]
### Description:
The latest version of bespoken 2.3.4 `bst` fails to run on my Mac, running node v11.9.0 . The script file `bst` uses a CLRF line ending on the shebang, which confuses the system as to what executable to run. Changing the line ending to LF fixes the problem. Also reverting to 2.1.17 works fine.

### Environment:
- Version: 2.3.4
- OS: MacOS 10.14.3
- Node version:  11.9.0

### Steps To Reproduce
1. include `"bespoken-tools": "2.3.4",` in package.json
2. `yarn`
3. `./node_modules/.bin/bst test`

### Expected behavior
I expect the tests to run

### Actual behavior
Error message:
`env: node\r: No such file or directory`

### Code example
N/A

**Comment by tripper54** [comment]
Note using v 2.3.4 also breaks tests on my circleCI setup (Debian).

**Comment by dmarvp** [comment]
hi @tripper54 thank you for reporting this, we'll take a look asap.

**Comment by MKen-li** [comment]
Marked as verified
