### ISSUE TITLE
Bst shows "Cannot read property 'includes' of undefined" 

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#575]
**Preconditions**
None.

**Steps To Reproduce**
1. Run a script with the operator "!=" on a property that returns null

**Expected behavior**
The system shows:
Received:
        undefined
on the failed utterance.

**Actual behavior**
The test shows the error "Cannot read property 'includes' of undefined" and is not executed

**Screenshots**
![bst error](https://user-images.githubusercontent.com/39920441/55116094-37ae0e80-50b4-11e9-9b43-175f5cff5003.png)

**Environment:**
- OS: Win 10
 - Version bespoken-tools@2.3.7

**Additional context**
Expected value at [property] to be one of:
This statement makes sense when using : or == but it doesn't when the operator is != Change message to 
Expected value at [property] to not be one of:

**Comment by ecruzado** [comment]
https://github.com/bespoken/skill-testing-ml/pull/205

**Comment by ecruzado** [comment]
can be tested on bespoken-tools@2.3.9

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.3.9
