### ISSUE TITLE
Automate our releases using Circle CI

### ISSUE THREAD

**Issue by jperata** [bespoken/bst#576]
**Is your feature request related to a problem? Please describe.**
BST releases require repeating the same process every time to deploy a new version, it also forces us to generate the version on a non-windows machine to avoid problems with the binaries creation.

**Describe the solution you'd like**
Automate the process using Circle-CI, so that we can generate Npm beta releases with a specific tag. This also removes the need to have code reviews for just version changes before doing a release (and the recurrent problem of having a different version in the code than the latest released beta). 

This should take into account skill-testing-ml since the code is deeply integrated on the bst-test side. We could generate a new skill-testing-ml beta release for each new beta on bst, so that we keep that as the correct case every time.

The bst version that we would publish as npm needs to be set up as part of the release (as part of the tag name or title) so that we can do not only patches but also minor and major version changes.

The change from beta to latest can be done manually. 

**Describe alternatives you've considered**
Keep the current process, but that has caused issues over time.
Have a process to do it that can be called from slack, that idea can still be used parting from this initial change.

**Additional context**
None

**Comment by ecruzado** [comment]
https://github.com/bespoken/bst/pull/594

**Comment by MKen-li** [comment]
Marked as verified
