### ISSUE TITLE
Add functionality to verify every assert per utterance in E2E testing

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#578]
**Preconditions**
None.

**Steps To Reproduce**
1. Create an E2E script with multiple asserts per utterances
2. The script has several failed assertions 
3. Run the script.

**Expected behavior**
1. Every assert is run regardless of the outcome showing in the console the result for each failed assertion.
2. This behavior should only be overwritten when using functionalities like Goto and Exit 
3. This is only applicable for e2e test scripts

**Actual behavior**
When an assert fails the others aren't executed

**Screenshots**
None.

**Environment:**
- OS: Win 10
- Build: bespoken-tools@2.3.9

**Additional context**
None.

**Comment by jperata** [comment]
Errors documentation from the API side
https://bespoken.github.io/skill-testing-ml/api/InteractionResult.html

**Comment by MKen-li** [comment]
Moving back to dev.

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.0
