### ISSUE TITLE
Remove libraries warnings on installation

### ISSUE THREAD

**Issue by jperata** [bespoken/bst#581]
### Description:
Because of some of our dependencies, we have some warnings during installation. We should remove those by updating the relevant libraries, there are a couple that we may not be able to remove if the latest version that we use is the one that has the warning.

### Environment:
- Version: 2.3.15
- OS: [e.g. Windows 10]
- Node version: 10 (it reproduces with other versions but this is the most accurate vulnerabilities report)

### Steps To Reproduce
1. Install the latest version of bespoken-tools
2. See the console

### Expected behavior
Bst is installed correctly with no warnings

### Actual behavior
Warnings are showed on vulnerabilities

### Additional context
Because this is a npm dependencies, we may have to update not only bst and skill-testing but our different minor projects to clean up all (virtual-device-sdk, virtual-alexa, etc). This ticket will keep track of the different updates.

**Comment by MKen-li** [comment]
closing ticket
