### ISSUE TITLE
Slot validation with bst test

### ISSUE THREAD

**Issue by habuma** [bespoken/bst#582]
After adding support for slot validation (see https://developer.amazon.com/docs/custom-skills/validate-slot-values.html#json-validation-rules) to my skill, I wanted to be able too test those validations with `bst test` and without having to deploy my skill. As far as I can tell, `bst test` does not apply validation to slot values.

For example, when I configure a validation of type "hasEntityResolutionMatch" to a slot, I'd expect that testing an intent with a value not included as part of the entity to not be accepted and result in a response containing one of the prompts associated with that validation rule. For example, if the slot type is a list type containing several types of fruit, then I'd expect validation to fail if the slot value given were "basketball" and to receive a prompt something like "Basketball isn't a fruit. Try again." (or some other prompt defined in the "prompts" section of the interaction model.

I recognize that to support validation testing like that, `bst test` would need to mimic functionality defined by the platform and perhaps it is out of scope for `bst test` to do that. If so, then what would you recommend as the best tactic for testing slot validation?

**Comment by jkelvie** [comment]
Hi @habuma - our end-to-end testing will certainly work for slot validation testing. It has the benefit that it will test using the real Alexa, so that the behavior is exactly the same as talking to an actual device.

Docs for end-to-end testing are here:
https://read.bespoken.io/end-to-end/getting-started

Of course, to use Alexa, it does require your skill and interaction model actually be deployed, so it is a bit cumbersome as a form of automated unit-testing. 

Adding slot validation rules is not outside what we seek to do with Virtual Alexa - we do mimic parts of Alexa's internal behavior, obviously. But we do not do all of them, and we, of course, cannot guarantee to do them all correctly. The slot validation rules are not something we have had a chance to add yet, and so far, this is the first request we have had to support it.

**Comment by habuma** [comment]
Thanks. I expected that end-to-end testing would work, but as you said, it's more cumbersome to deploy first to confirm that validation works. It'd be nice to be able to rapidly and frequently run tests against my skill using Virtual Alexa *before* deploying and then deploy and do end-to-end testing as a check once I'm satisfied with my work locally.  (I've not tried elicitation yet, but the same would go for that.)

**Comment by jkelvie** [comment]
Yes, I agree these are all very useful situations to support. Though in the first case you mention, is your primary concern ensuring that the interaction model is structured correctly? Or is to test your skill code on the calls going back and forth during dialog delegation? I'm guessing the former, but just checking.

**Comment by habuma** [comment]
Yes, my primary concern is ensuring that my interaction model is structured correctly. That is, I have enabled automatic delegation, along with some validation and elicitation and some dialogs to present if validation/elicitation fails. I want to know that I set that up correctly without having to deploy first.

**Comment by habuma** [comment]
Is it correct to say that the same holds true for slot elicitation? My initial attempts at testing dialog for both validation and elicitation have ultimately resulted in the fulfillment handler being invoked, rather than being handled automatically with prompts defined in the interaction model. (I suspect this to be true...just confirming.)

**Comment by jkelvie** [comment]
Yes, that is correct - we should probably make the disclaimer on this page more prominent:
https://github.com/bespoken/virtual-alexa/blob/master/docs/Dialog.md

But we do not emulate the internal dynamics of the DialogManager at this point.

This is something we have on our roadmap, but it's not scheduled at this time.

**Comment by habuma** [comment]
Understood. I'll patiently wait. :)

But first, one other reason this would be super handy (and has bit me in the last 24 hours) is that I can set it up so that every change to my interaction model triggers a run of tests and I get near-instant feedback to tell me if my change broke anything, enabling me (with recent knowledge) of the change to undo or fix it. Without the ability to test the model, I won't know until I deploy it and I'm not as likely to deploy it on every save, so by the time I am able to test the model, I may have made several changes and won't know which one broke my tests.

But, as I said, I'll patiently wait for the roadmap to run its course.

**Comment by jkelvie** [comment]
Understood - we'll let you know once this gets scheduled.
