### ISSUE TITLE
Support tags on a test suite level

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#603]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to assign tags on a test suite level so I can execute multiple selected test suite as needed

**Describe the solution you'd like**
Using the same property "tags" we want to add that on the configuration level of the test suite.

**Acceptances criteria**
1. GIVEN I set a tag for 1 or more test suites and I add the tag to the exclude group
WHEN I execute the bst command
THEN: All test inside the test suite excluded aren't executed

2. GIVEN I set a tag for 1 or more test suites and I add the tag to the include group
WHEN I execute the bst command
THEN: All test inside the test suite excluded are executed

3. GIVEN I include and exclude the same tag
WHEN I execute the bst command
THEN: no test is executed because the excludes takes priority

**Example**
I set the next scenario
Name: TestSuiteA
tags: TSA
test1 tags: A
test2 tags: B
test3 tags: C

Name: TestSuiteB
tags: TSA
test1 tags: A
test2 tags: B
test3 tags: C

I run the bst command using the testing.json to set the include/exclude or using the overwrite parameters feature like "bst test --include TSA --exclude B fileLocation"

The test executed are:
TestSuiteA
test1
test3
TestSuiteB
test1
test3

**Additional Information**
For AC 1 and 2 no verification is needed on a tag test level

**Comment by ecruzado** [comment]
https://github.com/bespoken/skill-testing-ml/pull/296

**Comment by MKen-li** [comment]
Marked as verified
Waiting for documentation update

**Comment by ecruzado** [comment]
https://github.com/bespoken/bespoken-docs/pull/68/files

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.6
