### ISSUE TITLE
When using include with a wrong tag all test that have a tag are executed

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#605]
**Preconditions**
Have some test set with tags

**Steps To Reproduce**
1. Run bst setting include feature but with a value of a tag that doesn't exist

**Expected behavior**
All test are skip because no test belong to that tag

**Actual behavior**
All test that has tags are executed

**Screenshots**
None.

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version bespoken-tools@2.4.4

**Additional context**
None.

**Comment by ecruzado** [comment]
https://github.com/bespoken/skill-testing-ml/pull/296

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.6
