### ISSUE TITLE
Mocking the user profile service

### ISSUE THREAD

**Issue by habuma** [bespoken/bst#606]
**Is your feature request related to a problem? Please describe.**
I'd like to test a skill that uses the UPS (e.g., `serviceClientFactory.getUpsServiceClient()` to fetch a user's name, email, and/or mobile number.

**Describe the solution you'd like**
BST's YML format already supports mocking of the device address, both full and partial by setting those details in the test specification's configuration. I'd like similar support for mocking the user's profile information that can be obtained via the user profile service.

**Describe alternatives you've considered**
I've considered writing an interceptor or using nock or some such thing to mock this out, but that would be more work than simply setting a few properties in the YML specification as BST supports for the device address.

**Additional context**
No additional context, other than I recognize that this might be more relevant to Virtual Alexa, as I can see from the source code that is where the device address configuration is handled. But I thought I'd start here as it is the `bst` tool that I use directly. If need be, I can close this issue and resubmit it in the Virtual Alexa project.

**Comment by habuma** [comment]
FWIW, I was able to mock the given name using a filter like this:

```const nock = require('nock');

module.exports = {
    onRequest: (test, requestEnvelope) => {
        const TEST_API_ENDPOINT = 'https://api.endpoint.com';

        // setup the API endpoint and token in the request
        requestEnvelope.context.System.apiEndpoint = TEST_API_ENDPOINT;
        requestEnvelope.context.System.apiAccessToken = "AUTHORIZED_TOKEN";

        // mock the givenName endpoint if the test is configured as authorized
        const upsAuthorized = test.testSuite.configuration.upsAuthorized 
            && test.testSuite.configuration.upsAuthorized.toString() === 'true';
        if (upsAuthorized) {
            nock(TEST_API_ENDPOINT)
                .get('/v2/accounts/~current/settings/Profile.givenName')
                .reply(200, '"Craig"', {'Content-Type': 'text/plain',});
        }
    }
};```

...and by setting `upsAuthorized` in a test suite like this:

```
---
configuration:
  locales: en-US
  filter: mock-ups-filter.js
  upsAuthorized: true
```

However, that's still not as convenient as it would be if I could just configure the given name like this:

```
---
configuration:
  locales: en-US
  givenName: Craig
```

**Comment by jkelvie** [comment]
Craig, thanks for submitting this. We are not planning this for the near-term sprints but will be considering it for our Q4 planning @dmarvp - we have some other requests of a similar nature to incorporate more mocks directly into the library.

**Comment by habuma** [comment]
That's awesome to hear it might in Q4 planning. I anxiously await its arrival.

In the meantime, I thought you might be interested to know that I evolved my filter slightly:

```
const nock = require('nock');

module.exports = {
  onRequest: (test, requestEnvelope) => {
    const mockGivenName = test.testSuite.configuration.givenName;
    const TEST_API_ENDPOINT = 'https://api.endpoint.com';
    requestEnvelope.context.System.apiEndpoint = TEST_API_ENDPOINT;
    requestEnvelope.context.System.apiAccessToken = 'API_ACCESS_TOKEN';
    if (mockGivenName) {
      nock(TEST_API_ENDPOINT)
          .get('/v2/accounts/~current/settings/Profile.givenName')
          .reply(200, `"${mockGivenName}"`);
    } else {
      nock(TEST_API_ENDPOINT)
          .get('/v2/accounts/~current/settings/Profile.givenName')
          .reply(403,
              {
                "code":"ACCESS_DENIED",
                "message":"Access denied with reason: FORBIDDEN"
              });
    }
  }
};
```

This lets me specify the given name in the test suite like this:

```
---
configuration:
  locales: en-US
  filter: mock-given-name-filter.js
  givenName: Craig
```

If the filter is in play and assuming that `givenName` is specified, then it injects a fake access token into the request and mocks the given name endpoint. Otherwise, you get a 403 quite similar to what you'd get in a deployed skill if permission to request the given name is not granted.

Of course, all of that just to test the given name from the UPS service. I'd need to recreate something like that for email, phone number, or any of the other endpoints.

**Comment by jperata** [comment]
[mockProfileTest.zip](https://github.com/bespoken/bst/files/4099755/mockProfileTest.zip)
Attaching a sample project, you can do console.log on the responses on the index.js to verify the 403 errors

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.34
