### ISSUE TITLE
Remove docs.bespoken.io from search engine web crawlers 

### ISSUE THREAD

**Issue by jperata** [bespoken/bst#609]
**Is your feature request related to a problem? Please describe.**
Our docs shouldn't be indexed by search engine web crawlers, it overlaps with the official documentation at read.bespoken.io

**Describe the solution you'd like**
Ensure the documentation generates a meta tag (name=robots, content=no-index)
https://developers.google.com/search/reference/robots_meta_tag

**Describe alternatives you've considered**
Just using the robot.txt is discouraged since it is still indexed but will show no information
https://support.google.com/webmasters/answer/6062608

**Additional context**
The docs is generated, we need to generate the meta tag in the head of the generated html via markdown supported by github/readthedocs

**Comment by jricaldi** [comment]
it already deployed in github page, but the google bot will take some time to recognize the new meta, in the meanwhile, you can see the source page(ctrl + U) and see the new meta tag `<meta name="robots" content="noindex" />`

**Comment by MKen-li** [comment]
Closing ticket, no QA needed
