### ISSUE TITLE
Bespoken report issues

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#612]
**Preconditions**
Run a test that has:
1. Skip tests
2. At least two tests with the same name

**Steps To Reproduce**
1. Run a test with the preconditions mention above
2. Open the bespoken report

**Expected behavior**
1. The pending test should say "pending" centered @jperata 
2. Each test is separate from the other even when 2 or more test have the same name

**Actual behavior**
1. The pending label is displayed but is not centered
2. The tests with the same name are combined in the report

**Screenshots**
None.

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version bespoken-tools@2.4.15

**Additional context**
None.

**Comment by jperata** [comment]
Available on latest beta (2.4.17)

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.17
