### ISSUE TITLE
bst speak doesn't work with others locales

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#614]
### Environment:
- Version: bespoken-tools@2.4.19
- OS: Windows 10
- Node version: 8.11.2

### Steps To Reproduce
1. set the locale with -l to any other than en-US
2. Run the test

### Expected behavior
The test works correctly

### Actual behavior
For any locale that is not the default or set to en-US the test doesn't work

**Comment by ig-perez** [comment]
Can we give this ticket high priority? It was reported by one of our paying users (Ruben from Wakeword). He also experienced the issue that was not allowing him to create virtual devices, so his perception might be degraded. Thanks!

**Comment by jperata** [comment]
Works in latest beta, with --voiceId
but it still doesn't work without voiceId due 
https://github.com/bespoken/virtual-device/issues/362

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.22
