### ISSUE TITLE
Update bst Init testing.json file

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#624]
**Is your feature request related to a problem? Please describe.**
We need to update this feature after the changes made in https://github.com/bespoken/skill-testing-ml/issues/324

**Describe the solution you'd like**
While doing the bst init we need to place the testing.json file in the root folder

**Additional context**
This will also required an update in the documentation.

**Comment by jkelvie** [comment]
Is this still necessary given the backwards compatibility approach we identified?

**Comment by dmarvp** [comment]
@jkelvie I don't think so, but as a general rule for bst init maybe we should move the testing.json to the root folder? when bst init was created it was put in a /test folder, but I understood that in general most of our users put it in the root? What are your thoughts on this?

**Comment by jkelvie** [comment]
I agree root folder is best

**Comment by habuma** [comment]
I'm curious: What are the reasons for it being in the root folder. I actually kinda like it being under /test, as it is testing-specific and is one less bit of clutter in the root. If there's a good reason for it to be in the root, that's fine, but I just want to understand that reason.

**Comment by jricaldi** [comment]
@MKen-li test it using v2.4.32

**Comment by MKen-li** [comment]
Marked as verified
Build = 2.4.33

**Comment by jperata** [comment]
Hi @habuma on the testing.json being on the root folder, we believe it makes it more clear to get the paths to the tests, filters and configuration files. It is also easier to check-in only the tests without checking private information like the virtual device token. 
But if that's not your style, you can set up the configuration inside the tests. We even added a new option to set up the context and the configuration location.
https://read.bespoken.io/unit-testing/guide/#custom-configuration-path-and-context
