### ISSUE TITLE
The system doesn't log any information when the test is skipped for an error

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#626]
### Description:
When have the property "ignoreExternalErrors" set on true the test is skipped when an error occurs but doesn't log any information of that happening making the users 

### Steps To Reproduce
1. set the flag "ignoreExternalErrors" to true
2. simulate an error in aws
3. notice that the test is skipped

### Expected behavior
bst-debug should have the next record 
"[info] ignoreExternalErrors is enabled. Skipping test <name of the test> because it failed with the following error: <error message>"

### Actual behavior
The test is skipped and no log is created for that action

### Environment:
- Version: bespoken-tools@2.4.30
- OS: Windows 10
- Node version: 8.11

### Additional context
None

**Comment by ecruzado** [comment]
https://github.com/bespoken/skill-testing-ml/pull/364

**Comment by ecruzado** [comment]
can be tested on version 2.4.43

**Comment by MKen-li** [comment]
Marked as blocked,  
waiting for  https://github.com/bespoken/skill-testing-ml/issues/365

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.47
