### ISSUE TITLE
JSON file are executed 

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#630]
### Description:
When selecting a folder to run it doesn't just run the YML files.

### Preconditions
1. None.

### Steps To Reproduce
1. Use the bst command and point to a folder that has YML files and also Json files

### Expected behavior
Only the YML files are executed

### Actual behavior
All is executed

### Environment:
- Version: bespoken-tools@2.4.32
- OS: Windows 10
- Node version: 8.11

### Additional context
Now that we are saving the result in Mongo, the execution of the JSON files are being also saved

**Comment by jricaldi** [comment]
@MKen-li test it with bst v2.4.40

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.40
