### ISSUE TITLE
e2e tests hide exception errors with "error description missing"

### ISSUE THREAD

**Issue by jperata** [bespoken/bst#632]
### Description:
e2e tests validate the errors that received from virtual device server and output the message they contain. If there is an exception it should print the error from the exception. We know that we are getting the errors because those are printed in the bst-debug.log file. 

### Environment:
- Version: 2.4.33
- Node: v10.16.3

### Steps To Reproduce
1.  Run a e2e yml script
2. Disconnect from the internet in the middle of the run

### Expected behavior
The user is shown an error from what the client detected (ETIMEOUT)

### Actual behavior
The user is shown the text "Error description missing", the ETIMEOUT is logged to bst-debug.log

### Additional context
The "ETIMEOUT" is ugly compared to the errors we generated from the virtual device, but give information to the user. "Error description missing" give no information and not all users are familiar with the bst-debug.log

**Comment by jperata** [comment]
Available on version 2.4.35

**Comment by jkelvie** [comment]
@MKen-li @jperata see my note here:
https://github.com/bespoken/skill-testing-ml/pull/347#issuecomment-578787078

**Comment by MKen-li** [comment]
Moving back to dev

**Comment by dmarvp** [comment]
Available on version 2.4.41

**Comment by dmarvp** [comment]
Verified.
