### ISSUE TITLE
Support for .env files

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#633]
**Is your feature request related to a problem? Please describe.**
Since enhancements have been done to the Jest Stare library that make use of env variables I need to set my env variables every time I want to make use of them.

**Describe the solution you'd like**
I think it would be a good idea to support .env files for easy manipulation of:
- Jest inline report
- Jest custom title
- etc

**Describe alternatives you've considered**
Putting them on the testing.json file, but since these are related to jest-stare only and that library only uses env variables, we would be going against their code style.

**Additional context**
I think .env files are supported internally already, so it would be a matter of importing that functionality on our releases.

**Comment by jricaldi** [comment]
@MKen-li changes on bst v2.4.38

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.39
