### ISSUE TITLE
Set Jest inline report to true by default

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#636]
**Is your feature request related to a problem? Please describe.**
The inline report is very useful, and forcing people to set an environment variable to use it is awkward. It should be enabled by default (though still able to be disabled by setting the environment variable to false).

**Describe the solution you'd like**
The inline report should be created by default for jest-stare.

**Comment by MKen-li** [comment]
Moving ticket back to dev.
We need to make the inline the only report available to the user

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.48
