### ISSUE TITLE
Add env property to indicate the location of the file

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#637]
### Summary

As a user of bespoken tools
I want to be able to have the env file in any location

### Acceptance Criteria

1. GIVEN: I have my env file in another location other than the root folder
WHEN: I run the bst test function with the --env + correct path 
THEN: The test uses the env properties set

2. GIVEN: I have my env file in another location other than the root folder
WHEN: I run the bst test function with the --env + invalid path 
THEN: The test doesn't use the env properties and a warning message is displayed @dmarvp 

3. GIVEN: I have my env file in another location other than the root folder and I have set the property "env": "correct path"
WHEN: I run the bst test function 
THEN: The test uses the env properties set

4. GIVEN: I have my env file in another location other than the root folder and I have set the property "env": "invalid path"
WHEN: I run the bst test function 
THEN: The test doesn't use the env properties and a warning message is displayed  ""

### NOTES

None.

**Comment by jperata** [comment]
Can be tested on bst 2.4.60
The final warning message is:
A .env file could not be found on: " + envLocation

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.61
