### ISSUE TITLE
Wrong URL displayed

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#639]
### Description:
None.

### Environment:
- Version: bespoken-tools@2.4.55
- OS: Windows 10
- Node version: 10.16.3

### Steps To Reproduce
1. Run a bst speak command for the first time

### Expected behavior
The URL displayed in the message is "https://apps.bespoken.io/dashboard/login"

### Actual behavior
The URL displayed in the message is "https://apps.bespoken.io/dashboard/skills/boring-bradbury-qGJC5o/validation" and that URL doesn't exist anymore

### Additional context
None.

**Comment by jperata** [comment]
Can be tested on bst v 2.4.56

**Comment by jperata** [comment]
According to conversation with @dmarvp and @MKen-li we are going to use just https://apps.bespoken.io/
because if the user is not logged in the virtual device url will redirect him to the login and then to skills.

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.56
