### ISSUE TITLE
Required parameter "opts.to" missing is displayed when a phone is not provided

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#646]
### Description:
When working with a Twilio platform the system shows the error "Required parameter "opts.to" missing" when a phone number is not provided

### Environment:
- Version: bespoken-tools@2.4.58
- OS: Windows 10
- Node version: 10.16.3

### Steps To Reproduce
1.  Set up a script for a Twilio app
2. Don't enter a phone number 
3. Run a test

### Expected behavior
The system shows the message @dmarvp "" only one time 

### Actual behavior
The system shows the message for each utterance "Required parameter "opts.to" missing." 

### Screenshot
![phone ivr](https://user-images.githubusercontent.com/39920441/79380136-98112780-7f25-11ea-87c8-93c58343c717.png)

### Additional context
None.

**Comment by dmarvp** [comment]
We should use a similar message as others when a required parameter is missing. For example, what message do we use if no virtual device token is set?

**Comment by MKen-li** [comment]
A valid virtualDeviceToken property must be defined either in the testing.json or the yml test file under the config element

**Comment by jperata** [comment]
Can be tested on version 2.4.62

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.62
