### ISSUE TITLE
when 'config' parameter is used upward, `bst test seems not to resolve path correctly

### ISSUE THREAD

**Issue by ThomasVuillaume** [bespoken/bst#649]
Hello everyone, and thanks for this great opensource framework !
I came across some difficulties, maybe I'm missing something but I tried some differents options without success. Let me describe it below.

Thank for the help ! 

### Description:
I have the following tree, according to the fact that I use the ASK v2 Hello World example : 

```text
.
├ test
 |  └ unit
 |      └ index.test.yml
 testing.json
├ lambda
 |  └ index.js
 |  ....
 |  └ package.json
```

I configured everything in the testing.json file, in order to have it working great, as soon as I launch the command `bst test` from the root folder.
What I'm trying to achieve is : launch the command `bst test`from the lambda folder (in fact it will be triggered from a package.json script) without touching anything.
I tried to path the `--config ../testing.json` argument, which is working becasue I have no warning about not-found testing.json. But the test suites does not start, and the pattern shows 0 match : 

```bash
testMatch: **/test/*.yml, **/tests/*.yml, **/*.e2e.yml, **/*.spec.yml, **/*.test.yml - 0 matches
  testPathIgnorePatterns: \\coverage\\, \\locales\\, \\lambda\\, \\test_output\\ - 0 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
```

I'm a bit surprise because the documentation says that "By default the context to resolve custom paths are relative to the location of the testing.json file." so I expected it to work like this. I tried to set a "--context" argument with different values, without succes.

### Environment:
- Version: BST: v2.4.65 
- OS: Windows 10
- Node version: Node: v12.14.1

### Steps To Reproduce
1. Have the `bst test` command to work from the root tree
2. Try to launch it from a subfolder, with the "--config ../testing.json" parameter
3. See that no test is found

### Expected behavior
Test suites that start. More precisely, that paths are correctly resolved to find the test files.

### Actual behavior
The paths seems to be incorrect as no tests is found.

### Code example
```javascript
let code = "copy your code in here!";
```
 **or:** attach a minimal version of your project where the issue is reproducible.

### Additional context
ASK CLI v2, with manual configuration that works : 

```json
{
  "handler": "lambda/.build/index.js",
  "locales": "en-US",
  "interactionModel": "skill-package/interactionModels/custom/en-US.json",
  "trace": false,
  "jest": {
    "collectCoverage": true,
    "collectCoverageFrom": [
      "lambda/.build/**/*.js",
      "!lambda/**/*.js",
      "!**/coverage/**",
      "!**/node_modules/**",
      "!**/vendor/**"
    ],
    "coverageDirectory": "./test_output/coverage/",
    "moduleFileExtensions": ["ts", "js", "yml"],
    "silent": false,
    "testMatch": [
      "**/test/*.yml",
      "**/tests/*.yml",
      "**/*.e2e.yml",
      "**/*.spec.yml",
      "**/*.test.yml"
    ],
    "verbose": true
  }
}
```

![image](https://user-images.githubusercontent.com/25711113/80962262-04889380-8e0d-11ea-8667-b170c322a274.png)

**Comment by dmarvp** [comment]
Hi @ThomasVuillaume! thanks for reporting this. We'll try to take a look soon.

**Comment by ThomasVuillaume** [comment]
You're welcome, good luck investigating !

In the meantime, I'm going over this by doing this in  my `package.json` (which is obviously awful 😂 )

```
    "scripts": {
        "build": "tsc",
        "test:unit": "npm run build && cd .. && bst test && cd -"
    },
```

**Comment by dmarvp** [comment]
Hi @ThomasVuillaume starting on bst version 2.4.68 you should be able to reach your tests the way you wanted by doing `bst test --config ../test/testing.json`. I'm closing the issue now but feel free to reach out if you find something else. Thanks!
