### ISSUE TITLE
update bst init for "Phone" virtual devices

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#666]
### Description:
Bst init mentions "IVR" multiple times.

### Environment:
- Version: 2.4.90

### Steps To Reproduce
1. Run bst init and select end to end tests

### Expected behavior
"Phone" is the third option.

### Actual behavior
- "IVR" is the third option.
- The "platform" property is set to "phone" in the resulting testing.json

**Comment by ecruzado** [comment]
https://github.com/bespoken/bst/pull/669/files

**Comment by dmarvp** [comment]
> Are you developing for Alexa, Google, or an IVR system?
should be changed to
> Are you developing for Alexa, Google, or an automated Phone system?

**Comment by ecruzado** [comment]
https://github.com/bespoken/bst/pull/670

**Comment by dmarvp** [comment]
Verified in dev.
