### ISSUE TITLE
Support request: Heroku docs/support?

### ISSUE THREAD

**Issue by pataquets** [bespoken/bst#686]
I've searched the repo looking for Heroku deployment info, with no luck.
Is Heroku deployment possible and/or supported?
If it's just missing docs, it would be interesting to mention it somewhere, at least. Repo is just tagged for GCP & AWS, too.

**Comment by jkelvie** [comment]
Hi, what/how are you trying to deploy on Heroku? We have not done any testing on that platform but I do not see any reason why our software should not work on it.

**Comment by pataquets** [comment]
Just wanting to make sure before trying, since most tutorials assume deploying on AWS/GCP.
Thank you.
