### ISSUE TITLE
Alexa emulator errors to handle - invalid URL

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#96]
"request": {
    "type": "SessionEndedRequest",
    "requestId": "amzn1.echo-api.request.ce43f17d-7f98-461c-94af-41f3f7d5b933",
    "timestamp": "2016-09-30T17:54:46Z",
    "locale": "en-US",
    "reason": "ERROR",
    "error": {
      "type": "INVALID_RESPONSE",
      "message": "The URL specified in the Play directive must be HTTPS"
    }

**Comment by jperata** [comment]
Closed by #117
